### ISSUE TITLE
More errors in Fedora

### ISSUE THREAD

**Issue by MikeDawg** [trustedsec/ptf#104]
Hi, saw you made the update to issue #98. Running into new issue:

ptf> use modules/install_update_all
[*] You are about to install/update everything. Proceed? [yes/no]:yes
[*] Auto updating is turned to on, this will install normal package updates for you...
[*] If you want to turn this off, go to the PTF directory and go to config and change AUTO_UPDATE
[*] Finished with normal package updates, moving on to the tools section..
[*] We are going to first install all prereqs using apt before installing..
[*] Cycling through modules and grabbing requirements...
[!] Warning, module modules/intelligence-gathering/eyewitness was found but contains no FEDORA field.
[!] Check the module again for errors and try again.
[!] Module has been removed from the list.
[!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.
[!] It's not possible its due to my coding skillz, it must be you? :-)
[!] Printing that error. Get that error. You get it: cannot concatenate 'str' and 'NoneType' objects

**Comment by trustedsec** [comment]
Fixed, can you test it? If having issues, I'll download Fedora and test.

**Comment by MikeDawg** [comment]
Testing now. Packages are building, and everything is going according to plan. I will update once install is completed.

I don't want you to have to go through the extra effort of installing Fedora.
