### ISSUE TITLE
Please add xdotool.

### ISSUE THREAD

**Issue by leebaird** [trustedsec/ptf#107]
Please add xdotool and add to the PATH.

**Comment by trustedsec** [comment]
Is there a specific depend for this? Isn't a pentesters tool off hand - more for mouse scripting.

**Comment by leebaird** [comment]
This is how I control the Terminal to open multiple tab, with each tab performing a different task. See Discover - option Nikto.

**Comment by trustedsec** [comment]
Added it as a depend in discover.
