### ISSUE TITLE
Error when starting Firefox from the command line.

### ISSUE THREAD

**Issue by leebaird** [trustedsec/ptf#109]
I believe this is an upstream issue.

root@ptf:~# firefox &
[1] 31503
root@ptf:~# 
(process:31503): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Gtk-Message: Failed to load module "canberra-gtk-module"
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node

**Comment by trustedsec** [comment]
PTF doesn't install or use Firefox.
