### ISSUE TITLE
List of tools/modules in the readme

### ISSUE THREAD

**Issue by danielmiessler** [trustedsec/ptf#116]
Is it possible to list the 109(+) modules in the readme, or somewhere else in a flat way? Seems like the only way to see everything now is to go into each directory and check them out. Would be cool to just see what all is included.

THANKS!

Great project.

**Comment by trustedsec** [comment]
If you go into PTF and run show modules will list all of the tools

**Comment by danielmiessler** [comment]
Indeed. I was thinking more before someone installs it. But yeah, that works.

**Comment by trustedsec** [comment]
"show modules" will list all the modules before installing them and everything :-)

ptf> show modules


The PenTesters Framework Modules
=================================

   Name                                                 Description 
   ----                                                 ---------------
    
   modules/install_update_all                           This will install or update all tools with modules within PTF
   modules/reporting/keepnote                           This module will install/update keepnote - note taking software
   modules/reporting/dradisframework                    This module will install/update - Dradis is a collaboration and reporting platform
   modules/wireless/ghost-phisher                       This module will install/update ghost-phisher - emulate access points and deploy various internal networking servers for networking, penetration testing and phishing attacks.
   modules/wireless/dot11decrypt                        This module will install/update dot11decrypt, a WEP/WPA2(AES and TKIP) on-the-fly decrypter.
   modules/wireless/aircrackng                          This module will install/update aircrack-ng, a tool for wireless attacks
   modules/wireless/kismet                              This module will install/update kismet, a tool for wireless auditing
   modules/wireless/wifite                              This module will install/update wifite - a tool for wireless auditing
   modules/wireless/airpwnng                            This module will install/update airpwn-ng, a tool for 802.11 packet injection & cookie grabbing
   modules/code-audit/rats                              This module will install/update rats, a tool for static C/C++ Code
   modules/code-audit/cfr                               This module will install/update cfr, a tool for decompiling java classes


<snip>
