### ISSUE TITLE
quiet install not functioning

### ISSUE THREAD

**Issue by stevemcquaid** [trustedsec/ptf#126]
https://github.com/trustedsec/ptf/blob/master/modules/vulnerability-analysis/dotdotpwn.py#L29

While `export PERL_MM_USE_DEFAULT=1` is set, during install user is still prompted to enter `yes` multiple times:

OUTPUT FROM SCRIPT:

CPAN.pm requires configuration, but most of it can be done automatically.
If you answer 'no' below, you will enter an interactive dialog for each
configuration option instead.

Would you like to configure as much as possible automatically? [yes] yes

Would you like me to automatically choose some CPAN mirror
sites for you? (This means connecting to the Internet) [yes] yes

ALSO:

[*] Pre-reqs for modules/vulnerability-analysis/openvas have been installed.
[*] Making the appropriate directory structure first
[*] SVN was the selected method for installation... Using SVN to install.
Error validating server certificate for 'https://scm.wald.intevation.org:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
Certificate information:
 - Hostname: wald.intevation.org
 - Valid: from Apr  9 18:16:41 2014 GMT until Apr  8 18:16:41 2016 GMT
 - Issuer: Intevation GmbH, DE
 - Fingerprint: 3B:AD:99:29:43:44:D4:97:15:2E:FB:EE:1C:5A:7E:A1:C4:BE:07:C8
(R)eject, accept (t)emporarily or accept (p)ermanently? p

**Comment by firebitsbr** [comment]
Checking...

**Comment by trustedsec** [comment]
This is actually do to OpenVAS and the certificate mismatch on SVN. I've fixed this by changing the SVN records to no cert check on this one only.
