### ISSUE TITLE
Hydra.py possible issue with hydra not running

### ISSUE THREAD

**Issue by d3ad7rack** [trustedsec/ptf#136]
Currently, when installed you can call hydra by typing hydra-wizard.sh, but when you get done entering in all of the values it errors out. In the python code, if I'm reading it correctly, hydra is supposed to be called with just 'hydra'

The issue may lie, again, if I'm reading the python code correctly, with 4th line from the bottom, at the end of the line "cd ../../,./configure,make,make install" am I right to assume that the comma in the ,./ could be messing it up?

**Comment by trustedsec** [comment]
Fixed by adding ldap-utils since build errors out on missing deps.
