### ISSUE TITLE
Issue with DradisFraimwork

### ISSUE THREAD

**Issue by Ka0s-M0nk3y** [trustedsec/ptf#150]
While installing PTF on a fresh Ubuntu 15.10 i am getting an error trying to install the dradisframework.

I have included a screen shot of the issue 

![screenshot from 2016-04-04 09-22-09](https://cloud.githubusercontent.com/assets/17013437/14258710/40e797b8-fa69-11e5-904f-3e7fc8a9881f.png)

**Comment by trustedsec** [comment]
Unable to reproduce - it looks like you didn't have an internet connection at the time and unable to download. Note its trying to get to the git location and was unable to communicate. When I run git, it works perfect.
