### ISSUE TITLE
/etc/apt/sources.list does not exist in whonix

### ISSUE THREAD

**Issue by kurobeats** [trustedsec/ptf#153]
Checking for the presence of /etc/apt/sources.list might not make sense for Debian based distros. I understand the script is trying to identify if it can use apt-get so perhaps change the following:

`if os.path.isfile("/etc/apt/sources.list"):`
to
`if os.path.isfile("/usr/bin/apt-get"):`

Further to this, Arch linux and Fedora would be better if the search for pacman and dnf is done rather than release.

**Comment by trustedsec** [comment]
Added - thanks for the suggestion!
