### ISSUE TITLE
Log file not being created

### ISSUE THREAD

**Issue by d3ad7rack** [trustedsec/ptf#164]
It's probably an oversight on my part, because I don't think I had an issue when I had ran the script on Ubuntu 14.04, but running it on 16.04, updated, I'm not getting a ptf.log file in src/logs/ when using modules/install_update_all

**Comment by trustedsec** [comment]
Logging isn't fully in yet - should be soon. I have the modules there just need to capture output. This is part of a larger thing I'm working on when things go amiss. Should have it done in next release!
