### ISSUE TITLE
Can you add Sn1per?

### ISSUE THREAD

**Issue by 1N3** [trustedsec/ptf#166]
https://github.com/1N3/Sn1per

**Comment by trustedsec** [comment]
I've started looking into this - it looks like its really built just for Kali for the most part. It looks to install specific modules that aren't in any other Ubuntu/Debian or distro repository:

apt-get install joomscan uniscan xprobe2 cutycapt unicornscan waffit host whois arachni theharvester dnsenum dirb dnsrecon curl nmap, etc.

I would recommend allowing the install options to specify the paths for these locations as most of these are already included in PTF just under the /pentest directory structure. Until then, I'm not sure its worth adding into it as most of the installation scripts seem focused on Kali.

**Comment by trustedsec** [comment]
I've still added the module since it does work and does basic recon on the beginning. Pushed to 1.7.2

**Comment by 1N3** [comment]
Thanks. I'll look at some options for including the paths in the next release and try to find some solutions for making this compatible with other distros...
