### ISSUE TITLE
wpscan requires ruby >= 2.1.9

### ISSUE THREAD

**Issue by zemb** [trustedsec/ptf#167]
wpscan is not possible to install via ptf:

[*] Sending after command: ruby wpscan.rb --update
Ruby >= 2.1.9 required to run wpscan (You have 2.1.5)

Tried on Kali and Ubuntu. Their repositories contain ruby 2.1.5.

**Comment by trustedsec** [comment]
Ruby versions usually lag behind in them. I would recommend switching to Ubuntu 16.04 LTS as it has a more maintained and updated ruby package. You can also upgrade ruby through ppa if you don't have something maintained through the Ubuntu or Kali repos:

https://www.brightbox.com/docs/ruby/ubuntu/

Test case below:

root@stronghold:/home/relik/Desktop/git/ptf# ruby -v
ruby 2.3.0p0 (2015-12-25) [x86_64-linux-gnu]

root@stronghold:/pentest/vulnerability-analysis/wpscan# ruby wpscan.rb --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[i] Update completed.
