### ISSUE TITLE
|| Unable to complete the Installation ||

### ISSUE THREAD

**Issue by neilkamulkar** [trustedsec/ptf#168]
Dear DDos,
Was performing full install of all the tools but was getting stucked up at a particular module of 

modules/intellegence-gathering/seclist 

as when it comes to installing this module nothing happens and does not go forward your help is appreicated ...

**Comment by trustedsec** [comment]
This was actually an old module and moved to pw recovery. I removed it and checked to ensure seclist was working. All seems fine and should be resolved. Thanks for the report!
