### ISSUE TITLE
Fresh arch install ptf will not execute

### ISSUE THREAD

**Issue by smokeless** [trustedsec/ptf#186]
$ sudo ./ptf
[*] You can always type ./ptf --no-network-connection to skip the Internet check..
[*] Checking for an Internet connection...
[*] Trying to update myself first.. Then starting framework.
Already up-to-date.
[!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.
[!] It's not possible its due to my coding skillz, it must be you? :-)
[!] Printing that error. Get that error. You get it: name 'file' is not defined

**Comment by trustedsec** [comment]
Looks like you are running this in python3 vs python2 - would recommend python2 as file operand is supported and has converted to open in python3. I've since changed this in version 1.8 so this should be resolved and released later next week.
