### ISSUE TITLE
Only post.php in /var/www after site cloning or site template (credential harvester)

### ISSUE THREAD

**Issue by shadycuz** [trustedsec/ptf#187]
I'm on Kali Rolling release. When I updated apt-get upgrade set, it said it was unpacking 7.2.3 but when running the version was listed as 7.2.2. I tried apt-get purge set and reinstalled but still reported 7.2.2. The first time I tried cloning a site it worked but when I typed in a fake username and password the post failed with  192.168.0.10/post.php  (nginx 405 error). I deleted the files out of /var/www and tried again but the only file created was post.php. I then used git to clone, ran set/settoolkit from the 7.2.3 git clone and still no files are created expect for post.php.

**Comment by trustedsec** [comment]
This is the wrong section - this would be for the PenTesters Framework (PTF) - not for the Social-Engineer Toolkit. 

Not sure what to say on that front, in a Kali fully updated I'm able to get the index.html and post.php and create the site for credential harvester. Might be the site you are trying to clone - you can manually import them for problematic sites.
