### ISSUE TITLE
Tools not installing

### ISSUE THREAD

**Issue by andranik24** [trustedsec/ptf#189]
A lot of tools are not installing when I run the update all command. When I go into /pentest, the directories of the folders are there, but the actual tools are not. They fail to install during the script. Any suggestions?

**Comment by trustedsec** [comment]
What OS are you running and what tools? 

Also any log files or if you want to fix you can submit PR too.

**Comment by jaredhaight** [comment]
This is likely fixed with [my PR that just got merged](https://github.com/trustedsec/ptf/pull/188).

**Comment by andranik24** [comment]
Jared was right everything is working now. Thank you!
