### ISSUE TITLE
ptf not installing

### ISSUE THREAD

**Issue by valerysimonyan** [trustedsec/ptf#190]
[*] You can always type ./ptf --no-network-connection to skip the Internet check..
[*] Checking for an Internet connection...
[*] Trying to update myself first.. Then starting framework.
Already up-to-date.
[!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.
[!] It's not possible its due to my coding skillz, it must be you? :-)
[!] Printing that error. Get that error. You get it: [Errno 2] No such file or directory: '/usr/local/bin/ptf'

**Comment by trustedsec** [comment]
What OS is this?

**Comment by trustedsec** [comment]
Are you not running as root? the create launcher is what is erroring out:


# create launcher
def create_launcher():
    cwd = os.getcwd()
    filewrite = open("/usr/local/bin/ptf", "w")
    filewrite.write("#!/bin/sh\ncd %s\nchmod +x ptf\n./ptf $*" % (cwd))
    filewrite.close()
    subprocess.Popen("chmod +x /usr/local/bin/ptf", shell=True).wait()

It it's not there, it should create it unless you don't have the permissions to...

**Comment by Vivian-VV** [comment]
May be your OS is Kali Rolling (AMD64),SO ,you need to create the folder manually：use command：mkdir /usr/local/bin

**Comment by trustedsec** [comment]
I added an automatic creation for /usr/local/bin just in case :)
