### ISSUE TITLE
Wafw00f issue

### ISSUE THREAD

**Issue by niemant** [trustedsec/ptf#193]
Hello,
After using ptf, and running 

> ptf> use modules/install_update_all

Once finished, I tried to run wafw00f i got the following error

> wafw00f 
> Traceback (most recent call last):
>   File "/usr/local/bin/wafw00f", line 4, in <module>
>     __import__('pkg_resources').run_script('wafw00f==0.9.4', 'wafw00f')
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2928, in <module>
>     @_call_aside
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2914, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2941, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'pluginbase==0.3' distribution was not found and is required by wafw00f

I checked pluginbase and this what the response:

> pip install pluginbase
> Requirement already satisfied (use --upgrade to upgrade): pluginbase in /usr/local/lib/python2.7/dist-packages

Any Ideas?

Regards.

**Comment by trustedsec** [comment]
What OS are you using here? I just tested on 16.04 and seems to be okay

root@stronghold:/pentest/intelligence-gathering/waffit# wafw00f

                                 ^     ^
        _   __  _   ____ _   __  _    _   ____
       ///7/ /.' \ / __////7/ /,' \ ,' \ / __/
      | V V // o // _/ | V V // 0 // 0 // _/
      |_n_,'/_n_//_/   |_n_,' \_,' \_,'/_/
                                <
                                 ...'

    WAFW00F - Web Application Firewall Detection Tool

    By Sandro Gauci && Wendel G. Henrique

Usage: wafw00f url1 [url2 [url3 ... ]]
example: wafw00f http://www.victim.org/

wafw00f: error: we need a target site
root@stronghold:/pentest/intelligence-gathering/waffit# wafw00f https://www.trustedsec.com

                                 ^     ^
        _   __  _   ____ _   __  _    _   ____
       ///7/ /.' \ / __////7/ /,' \ ,' \ / __/
      | V V // o // _/ | V V // 0 // 0 // _/
      |_n_,'/_n_//_/   |_n_,' \_,' \_,'/_/
                                <
                                 ...'

    WAFW00F - Web Application Firewall Detection Tool

    By Sandro Gauci && Wendel G. Henrique

Checking https://www.trustedsec.com

**Comment by niemant** [comment]
I'm using Kali Linux Rolling.

**Comment by trustedsec** [comment]
Have you tried:

pip install pluginbase --upgrade? Looks like it might be an outdated version...

**Comment by niemant** [comment]
Yes It was one of the first things I tried:
pip install pluginbase --upgrade
Requirement already up-to-date: pluginbase in /usr/local/lib/python2.7/dist-packages
