### ISSUE TITLE
Re: Wafw00f issue

### ISSUE THREAD

**Issue by niemant** [trustedsec/ptf#196]
**Re Open**

It seems that **ptf> use modules/install_update_all,** broke the wafw00f install in Kali Linux Rolling.

The only way or running wafw00f successfully is going to:

**/pentest/intelligence-gathering/waffit/wafw00f/**
and running _**main.py**_

_ls_ on the folder:

> /pentest/intelligence-gathering/waffit/wafw00f# ls -ltrn
> total 48
> drwxr-xr-x 2 0 0  4096 jul 28 00:39 tests
> drwxr-xr-x 2 0 0  4096 jul 28 00:39 plugins
> -rw-r--r-- 1 0 0   628 jul 28 00:39 manager.py
> -rwxr-xr-x 1 0 0 20390 jul 28 00:39 main.py
> drwxr-xr-x 2 0 0  4096 jul 28 00:39 lib
> -rw-r--r-- 1 0 0    46 jul 28 00:39 __init__.py
> drwxr-xr-x 2 0 0  4096 jul 28 00:39 bin
> -rw-r--r-- 1 0 0   177 jul 28 00:39 __init__.pyc
> 

If I run it using the command wafw00f directly in that folder or any folder the error I get is:

> /pentest/intelligence-gathering/waffit/wafw00f# wafw00f 
> Traceback (most recent call last):
>   File "/usr/local/bin/wafw00f", line 4, in <module>
>     __import__('pkg_resources').run_script('wafw00f==0.9.4', 'wafw00f')
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2928, in <module>
>     @_call_aside
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2914, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2941, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'pluginbase==0.3' distribution was not found and is required by wafw00f
>

**Comment by trustedsec** [comment]
I've added pluginbase as a requirement in the latest version of PTF. You can simply type pip install pluginbase to resolve this issue. 

Thanks for the report.

**Comment by niemant** [comment]
Hi, As I mentioned before:

> pip install pluginbase
> Requirement already satisfied (use --upgrade to upgrade): pluginbase in /usr/local/lib/python2.7/dist-packages
> 

Regards

**Comment by trustedsec** [comment]
Then use pip install --upgrade. When I use it on Ubuntu it works fine. You could be using an out of date version of Python.

**Comment by trustedsec** [comment]
The error message is clear.

**Comment by niemant** [comment]
I do understand the error is clear, but again:

> pip install --upgrade pluginbase
> Requirement already up-to-date: pluginbase in /usr/local/lib/python2.7/dist-packages
> 
This happened when I "installed" ptf, is there any route of python that it modifies?

Thanks

**Comment by niemant** [comment]
When I run locate searching for pluginbase here is the result:
locate pluginbase

> /pentest/vulnerability-analysis/faraday/test_cases/pluginbase_api.py
> /usr/local/lib/python2.7/dist-packages/pluginbase-0.4.dist-info
> /usr/local/lib/python2.7/dist-packages/pluginbase.py
> /usr/local/lib/python2.7/dist-packages/pluginbase.pyc
> /usr/local/lib/python2.7/dist-packages/pluginbase-0.4.dist-info/DESCRIPTION.rst
> /usr/local/lib/python2.7/dist-packages/pluginbase-0.4.dist-info/INSTALLER
> /usr/local/lib/python2.7/dist-packages/pluginbase-0.4.dist-info/METADATA
> /usr/local/lib/python2.7/dist-packages/pluginbase-0.4.dist-info/RECORD
> /usr/local/lib/python2.7/dist-packages/pluginbase-0.4.dist-info/WHEEL
> /usr/local/lib/python2.7/dist-packages/pluginbase-0.4.dist-info/metadata.json
> /usr/local/lib/python2.7/dist-packages/pluginbase-0.4.dist-info/top_level.txt
> /usr/share/python-faraday/test_cases/pluginbase_api.py
>/usr/share/python-faraday/test_cases/pluginbase_api.pyc

I've also tried reinstalling wafw00f but I get the same error.

**Comment by niemant** [comment]
Solved it running again:

> ptf> use modules/install_update_all  

Thanks for your patience and assistance
