### ISSUE TITLE
whatweb broken :(

### ISSUE THREAD

**Issue by d3ad7rack** [trustedsec/ptf#198]
Seems as though the devs for whatweb had made some changes and changes made no longer make whatweb want to work with ruby 1.9. Getting "./whatweb: /usr/lib/ruby/vendor_ruby/rchardet/universaldetector.rb:39: invalid multibyte escape: /[\x80-\xFF]/ (SyntaxError)" while trying to run it now. There is a post on ubuntu forums about it, and I did create a temp fix by putting an 'n' at the end of the lines on lines 39 and 40, but not sure of a "real fix" at this time, other than that

**Comment by trustedsec** [comment]
I've included a patched version of universal detector and will include it into PTF.

**Comment by Seceventspen** [comment]
Hi guys,

Seems as though the  OP's issue above is back again!! Whatweb is no longer working with Ubuntu 16.04LTS and ruby package:

$ ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu] 

I'm getting "./whatweb: /usr/lib/ruby/vendor_ruby/rchardet/universaldetector.rb:39: invalid multibyte escape: /[\x80-\xFF]/ (SyntaxError)" while trying to run it now. 

Tried the previous fix mentioned above, appending the 'n' and Whatweb does run but spits out some verbose errors before returning the target info.

I've edited /usr/lib/ruby/vendor_ruby/rchardet/universaldetector.rb and placed the 'n' at the end of the following lines:

      @_highBitDetector = /[\x80-\xFF]/n
      @_escDetector = /(\033|\~\{)/n

Then rerun Whatweb with a target domain specified and get the following error line but with target data returned:

---[snip]---
$ whatweb m*************.com
/usr/share/whatweb/plugins/wordpress.rb:436: warning: key "2.7-beta1" is duplicated and overwritten on line 453
<<target whatweb  data removed>>

This error message appears regardless of domain or IP used, though now whatweb starts and functions.
