### ISSUE TITLE
depends!

### ISSUE THREAD

**Issue by freeload101** [trustedsec/ptf#204]
This is sort of a stupid one but depends don't include gcc  add apt-get install build-essential to depends :P   

BUMP

aircrack depends '"cannot find -lnl-genl-3"'   add  depends apt-get install libnl-genl-3-dev

BTW great work on this project ! let me know if you ever  need anything ! I got so sick of Kali and the rando repo ... I am trying to get my testers to use PTF and tell Kali to suck it gary!

**Comment by meldridge** [comment]
Not really the place for it, but I just wanted to echo thanks for this project - it's an awesome framework!

**Comment by thatrez** [comment]
Also not the place for it- but thanks so much!

**Comment by trustedsec** [comment]
Thanks you all! Much appreciated =)

**Comment by trustedsec** [comment]
Agree with @freeload101  here a bit - since a lot require it, I added it to initial startup and also fixed the aircrack-ng piece. Thanks!
