### ISSUE TITLE
README - IGNORE_THESE_MODULES syntax

### ISSUE THREAD

**Issue by Haydz** [trustedsec/ptf#205]
Hi Dave,

I was working on excluding modules being installed.

I noticed in the readme, the syntax is incorrect.

Currently it says:
"or entire module categories, like modules/code-audit/,/modules/reporting/"

When it should be:
"or entire module categories, like /modules/code-audit/*,/modules/reporting/*"
specifically missing the initial forward slash and star.

I tried to do a pull-request but failed >.<
My example is attached.

![ptf](https://cloud.githubusercontent.com/assets/2356349/17989265/139c148a-6afa-11e6-8188-398005867fa8.png)

**Comment by trustedsec** [comment]
Thanks for the PR, just merged it. Thank you :) 👍
