### ISSUE TITLE
Cowpatty and Pyrit

### ISSUE THREAD

**Issue by matrixfox** [trustedsec/ptf#209]
Not really an issue. I was just wondering why these two aren't supported. I saw Crunch and Hashcat, got all excited, then came back to earth.

**Comment by MikeDawg** [comment]
@matrixfox Go ahead and create the packages, and add it to the repo.

**Comment by trustedsec** [comment]
Can always add them, the framework is flexible and easy to add new ones :) If I get some time, I can add.

**Comment by matrixfox** [comment]
I'm having problems getting Cowpatty to work. I got Pyrit working... This must be a IQ test!

P.s. Thank you for writing this, saves tremendous amount of time!

**Comment by trustedsec** [comment]
Sweet thanks, added cowpatty and also added pyrit.
