### ISSUE TITLE
armitage parse error

### ISSUE THREAD

**Issue by thatrez** [trustedsec/ptf#214]
abandoned debian and switched over to xubuntu as you couldn't replicate the error.  Installed ptf then used metasploit installer and armitage installer in ptf. went to the armitage-unix folder and ran ./armitage 

got the same error as I did in debian. Please assist if you can. God knows RSmudge isn't going to help

![progress _002](https://cloud.githubusercontent.com/assets/7432967/18295022/db00f408-746b-11e6-9016-9b89ed745d69.png)

**Comment by mkannan22** [comment]
I am receiving the same error. I couldn't get armitage to launch using openjdk-9*, so I removed that version and installed version 8, which is when I see the error posted above. Using Ubuntu 16 x64.

**Comment by thatrez** [comment]
here are some things I've trixed - another fresh install xubuntu 16.04 apt-get update \ upgrade and installed git and build-essential. Clone PTF, install metasploit then armitage. Get error message related to JDK... replaced JDK with oracle JDK 8. Installed rbenv and rbenv sudo according to this https://gorails.com/setup/ubuntu/16.04 and https://github.com/dcarley/rbenv-sudo set ruby to 2.3.1. 
updated all gems. Read several posts on how this issue was supposed to be resolved back in 2015. https://github.com/rsmudge/armitage/issues/184
 
tried setting msgpack to different versions by editing theGemfile.lock and setting it to 
where it says: GEM remote  (0.5.12) and (0.6.0)

drank some vodka

passed out

**Comment by trustedsec** [comment]
Lol, let me see what I can do here. I don't mess with Armitage much, so I'm at a bit of a disadvantage here, but will give it a whirl.

**Comment by trustedsec** [comment]
Started working on this, have some more work to do.

**Comment by thatrez** [comment]
I managed to get it work on my system by removing metasploit installed by PTF and installing metasploit CE, then registering it. I would prefer to use the git version as it tends to be more up to date. I've recently switched over to empire so this isn't a priority anymore.

**Comment by trustedsec** [comment]
Yeah, I spent a lot of time on this one and didn't get it working, doesn't look like its much supported anymore. Going to close this for now and keep it as a priority as time commends. Thanks for the update.
