### ISSUE TITLE
Fluxion

### ISSUE THREAD

**Issue by BustedSec** [trustedsec/ptf#231]
requesting addition of https://github.com/deltaxflux/fluxion to wireless section

it needs https://github.com/aanarchyy/bully to work right, installs all other dependencies running built in installer script. 

Video showing tool - 
https://www.youtube.com/watch?v=Pc8JCiRZ-4w

**Comment by thatrez** [comment]
tried doing it myself, let me know if it is ok.

**Comment by thatrez** [comment]
I've tested it on debian, ubuntu, and mint. Seems to work on all 3

**Comment by trustedsec** [comment]
Looks great, works on mine as well. Thanks for the commit!
