### ISSUE TITLE
Missing requirement for CredCrack

### ISSUE THREAD

**Issue by Chewvala** [trustedsec/ptf#236]
Just a heads up, according to CredCrack's Readme "CredCrack solely relies on having PowerSploit's "Invoke-Mimikatz.ps1" under the /var/www directory. "
It's easy enough for someone to install, but wanted to let you know in case you weren't aware.

**Comment by BustedSec** [comment]
I'll work on this when I get home - I think I'll have it do a wget https://github.com/clymb3r/PowerShell/blob/master/Invoke-Mimikatz/Invoke-Mimikatz.ps1 and then a mv to the /var/www folder

**Comment by BustedSec** [comment]
pull request submitted for issue

**Comment by trustedsec** [comment]
Awesome work, thanks for the help :)
