### ISSUE TITLE
Are there any communities to join the project?

### ISSUE THREAD

**Issue by mikeSaidHi** [trustedsec/ptf#248]
As above, I'm currently looking for a community such as Discord.

Thanks! xD

**Comment by mikeSaidHi** [comment]
Or IRC ?

**Comment by BustedSec** [comment]
Not at this time.

**Comment by BustedSec** [comment]
I could throw up an XMPP server if Rel1k wants one.

**Comment by trustedsec** [comment]
Decided to create ##PTF on freenode.
