### ISSUE TITLE
Sparta errors when running

### ISSUE THREAD

**Issue by Xoke** [trustedsec/ptf#264]
On Ubuntu 10.04, installing sparta, and running sparta gives
_./sparta" line 2: cd: /usr/share/sparta/: No such file or directory_

To resolve, I ran
_ln -s /pentest/vulnerability-analysis/sparta /usr/share/sparta_

Sparta now loads and appears to run fine

**Comment by BustedSec** [comment]
nice !

**Comment by trustedsec** [comment]
successfully fixed in latest build, thanks!
