### ISSUE TITLE
Depends update ptf/modules/av-bypass/veil-framework.py

### ISSUE THREAD

**Issue by freeload101** [trustedsec/ptf#267]
Depends should be updated for msf and wine ! as veil ask for the path to MSF on install. Not sure howto do non apt based depends but the apt depend would be 

DEBIAN="git python-pycryptopp python-capstone metasploit-framework wine"

https://github.com/freeload101/ptf/blob/master/modules/av-bypass/veil-framework.py

**Comment by trustedsec** [comment]
There is an issue with this particular method. Metasploit-framework isn't in the repository for Ubuntu/Debian and is added after its already been installed. What I've done instead is release a new version 1.13 which now has a section called "TOOL_DEPENDS=" and in there you can specify other modules that are required prior to installing the tool. This should allow the ability to install Metasploit first, then prompt afterwards for Veil as its required to work. Thanks for the recommendation! I've also updated the veil package.
