### ISSUE TITLE
'fedora_modules' referenced before assignment

### ISSUE THREAD

**Issue by littleairmada** [trustedsec/ptf#268]
OS: Fedora 25
PTF: v1.13
Python: v2.7.13 (system default)

It looks like there was a change between 1.10 and 1.12 that neutered ptf on Fedora.  I may have missed the announcement but is ptf only supporting Ubuntu/Debian/Arch from now on?

Update: I'm seeing a `local variable 'fedora_modules' referenced before assignment` error but the issue only occurs when the `install_update_all` module is called.

```
# ./ptf --update-all
[...]
[!] Not running a Debian variant..
[*] Operating system detected as: FEDORA
[...]
[*] You are about to install/update everything. Proceed? [yes/no]:yes
[*] Auto updating is turned to on, this will install normal package updates for you...
[*] If you want to turn this off, go to the PTF directory and go to config and change AUTO_UPDATE
[*] Finished with normal package updates, moving on to the tools section..
[*] We are going to first install all prereqs using apt before installing..
[*] Cycling through modules and grabbing requirements...
[!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.
[!] It's not possible its due to my coding skillz, it must be you? :-)
[!] Printing that error. Get that error. You get it: local variable 'fedora_modules' referenced before assignment

```

**Comment by littleairmada** [comment]
...and I don't want to waste my time creating a patch if the plan is/was to drop Fedora support.  ;)

**Comment by trustedsec** [comment]
There's no plan on dropping Fedora :) It's a bug. Will take a peek.

**Comment by trustedsec** [comment]
This has been resolved and pushed a fix. Thanks for the report!

**Comment by littleairmada** [comment]
Thanks for the quick turnaround!
