### ISSUE TITLE
Not updating dependencies

### ISSUE THREAD

**Issue by Lexus89** [trustedsec/ptf#269]
When an already installed tool is updated, it does not first fix potentially updated dependencies. I had modified the birp module to install missing python-pip (it needs this) but it skips that install function when doing an update

**Comment by Lexus89** [comment]
Would also be great if other dependencies, currently installed with pip at after commands, could be set seperatly and also updated when running update. This makes it easier to work with the bypass_update parameter and easier to work with new dependencies.

**Comment by trustedsec** [comment]
Working on this one, will have it as a milestone
