### ISSUE TITLE
Dirb not creating an automatic launcher on install

### ISSUE THREAD

**Issue by oliverloveless** [trustedsec/ptf#284]
When installing the dirb module, an automatic launcher is not created. I believe this is because dirb does not contain a  file called 'dirb' when launcher() is run (before after_commands() has a chance to compile the source). 

As a solution, either the launcher function should trust that the an appropriate launcher file will be created during the after_commands() function, or launcher() should be run after after_commands() during the install process.

I recommend running the launcher() function after the after_commands() function.

NB: apologies for not referencing code etc, new to using GitHub and Git.

**Comment by oliverloveless** [comment]
Having checked the solution of switching launcher() and after_commands() in framework.py, I haven't found any issues with it, and it does solve the problem.

**Comment by BustedSec** [comment]
@oliverloveless can you show me what you mean by switching the launcher and after commands - I am unable to replicate that

**Comment by oliverloveless** [comment]
switching lines 432 and 433 in src/franework.py

**Comment by oliverloveless** [comment]
The issue is that ptf makes assumptions on whether the repo needs to be compiled before a launcher can be created.

ptf assumes that all git repos are not compiled, and therefore thinks it's ok to create the launcher, before the after_commands (as specified in the config file) are run. This causes an issue in any compiled tool originating from github, because they don't have the appropriately named executable file in the repository (which src.core.launcher() uses in the launcher creation process).

**Comment by BustedSec** [comment]
fix confirmed. Switching lines 431 and 432 in framework.py fixes issue. Will add fix to commit

**Comment by BustedSec** [comment]
this is fixed in my recent pull request
