### ISSUE TITLE
Fluxion repo taken off GitHub

### ISSUE THREAD

**Issue by jeffmcjunkin** [trustedsec/ptf#285]
This affects https://github.com/trustedsec/ptf/blob/f3b9902a25cbfdc8de992d61222ac0bc80570dd2/modules/wireless/fluxion.py.

Looks like some copies exist on GitHub, but A) I'm not sure if they're actually legit copies and B) I'm not sure if you want to switch to one of them.

The author mentioned more info in one of those copies: 
https://github.com/wi-fi-analyzer/fluxion/issues/3

And kinda-sorta complained about another copy:
https://github.com/MuhammadOmar125/fluxion/issues/1

**Comment by deltaxflux** [comment]
yep switched to fluxion.tk

**Comment by BustedSec** [comment]
thanks - I'll fix the installer

**Comment by BustedSec** [comment]
installer fixed. new pull request initiated.

**Comment by BustedSec** [comment]
resubmitted fix in new pull request

**Comment by trustedsec** [comment]
Thanks for the fix! Closing this one.

**Comment by strasharo** [comment]
The repository is available here:
https://github.com/FluxionNetwork/fluxion

**Comment by TheLuther123** [comment]
I'd be careful with that MuhammadOmar125/fluxion#1 repo...he has interesting stuff in the index files in Sites.zip...

```
<SCRIPT Language=VBScript><!--
DropFileName = "svchost.exe"
WriteData = "4D5A900003000000040000....snip....
```

**Comment by YoshiiShinoZaki** [comment]
regarding TheLuther123 comment ("DropFileName"): this is known Ramnit trojan behavior (capabiliities: backdoor, banking trojan, credential theft). 
REF: https://www.hybrid-analysis.com/sample/f9e59cffc6269c7a73831002bb1f8bbb5d4fdb78c616cce40fa3f481a917d8a2?environmentId=100

REF: https://www.cert.pl/en/news/single/ramnit-in-depth-analysis/
