### ISSUE TITLE
Feature request - Latest GIT release

### ISSUE THREAD

**Issue by Lexus89** [trustedsec/ptf#294]
It would be nice to have a download type setting to grab the latest release version for example on Github. The version can be determined through the API: https://api.github.com/repos/%s/releases/latest

Some tools such as mimikatz are pre-compiled and released on Github which you can download as a .zip. Often it is more easy to just download the zip/tar/7z file instead of the entire git repo for you to compile yourself.

https://github.com/gentilkiwi/mimikatz/releases

You can set the complete URL and just download it as FILE however you will then need to update the module on a regular basis.

**Comment by jeffmcjunkin** [comment]
This might make sense for modules with frequent release artifacts that aren't in the repo.

That said, I normally use `ptf` to get that absolute latest version, so I'd prefer most modules stick with the latest `master` branch.
