### ISSUE TITLE
msfconsole permissions issue on first run

### ISSUE THREAD

**Issue by BustedSec** [trustedsec/ptf#296]
The permissions of the .msf4 folder are set to the root user rather than the currently logged on user. This can be fixed by running `sudo chown -R `whoami` ~/.msf4` as the local user. I think using the same logic I could incorporate a fix using AFTER_COMMANDS like so `sudo chown -R 'sh -c 'echo $SUDO_USER' ~/.msf4`

This is a fresh install of ubuntu 16.04. These are the results of uname -a
`Linux Yennifer 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Example of issue
 During a first run of msfconsole this creates the following issue:

`Would you like to use and setup a new database (recommended)? yes
/opt/metasploit-framework/embedded/framework/msfdb:176:in `initialize': Permission denied @ rb_sysopen - /home/havok/.msf4/database.yml (Errno::EACCES)
	from /opt/metasploit-framework/embedded/framework/msfdb:176:in `open'
	from /opt/metasploit-framework/embedded/framework/msfdb:176:in `init_db'
	from /opt/metasploit-framework/embedded/framework/msfdb:277:in `<main>'

 ** Metasploit Framework Initial Setup Complete **

touch: cannot touch '/home/havok/.msf4/initial_setup_complete': Permission denied
Rails Error: Unable to access log file. Please ensure that /home/havok/.msf4/logs/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /home/havok/.msf4/logs/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
/opt/metasploit-framework/embedded/framework/lib/rex/logging/sinks/flatfile.rb:21:in `initialize': Permission denied @ rb_sysopen - /home/havok/.msf4/logs/framework.log (Errno::EACCES)
	from /opt/metasploit-framework/embedded/framework/lib/rex/logging/sinks/flatfile.rb:21:in `new'
	from /opt/metasploit-framework/embedded/framework/lib/rex/logging/sinks/flatfile.rb:21:in `initialize'
	from /opt/metasploit-framework/embedded/framework/lib/msf/base/logging.rb:24:in `new'
	from /opt/metasploit-framework/embedded/framework/lib/msf/base/logging.rb:24:in `init'
	from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework.rb:111:in `simplify'
	from /opt/metasploit-framework/embedded/framework/lib/msf/base/simple/framework.rb:73:in `create'
	from /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:74:in `initialize'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `new'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `driver'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:48:in `<main>'
`
Will work on a bugfix later - maybe this time someone will actually pull my fix... I'm looking at you Dave..

**Comment by trustedsec** [comment]
Hey! I pulled your fix :) When its all mangled, it takes me longer :)
