### ISSUE TITLE
Add joomlavs (Successor of joomscan)

### ISSUE THREAD

**Issue by xturumsx4z** [trustedsec/ptf#302]
Hello,

First off, thanks for this project it has been very useful.

I would like to have joomlavs (https://github.com/rastating/joomlavs) added as a module. I have a fork with a module written that I use already, if you would like me to do a pull request let me know.

Thanks.

**Comment by BustedSec** [comment]
I think that would be a great idea - looks like a cool project. Please submit a pull request. I'd like to see this tool in the framework.

**Comment by gazcbm** [comment]
Fixed by pull request https://github.com/trustedsec/ptf/pull/364

**Comment by tpltnt** [comment]
#364 has been merged. is this issue still current?
