### ISSUE TITLE
John the Ripper only runs as root, needs system-wide install

### ISSUE THREAD

**Issue by jeffmcjunkin** [trustedsec/ptf#307]
See https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/doc/README-DISTROS

Instead of the painful build chain with fallbacks in the above documentation, I ran the following command:
```
./configure CPPFLAGS='-DJOHN_SYSTEMWIDE -DJOHN_SYSTEMWIDE_EXEC="\"/usr/local/bin\"" -DJOHN_SYSTEMWIDE_HOME="\"/usr/local/share/john\""'  &&
make -s clean && make -sj`nproc` strip &&
rm -rf ../run/*.dSYM &&
sudo mv ../run/{john,john-*,*2john,unshadow,unique,undrop,unafs,base64conv,tgtsnarf,mkvcalcproba,genmkvpwd,calc_stat,raw2dyna,cprepair,SIPdump} /usr/local/bin &&
sudo mkdir -p /usr/local/share/john &&
sudo cp -a ../run/* /usr/local/share/john &&
sudo mv /usr/local/share/john/*.{pl,py,rb} /usr/local/share/john/{relbench,benchmark-unify,mailer,makechr} /usr/local/bin
```

It's based on the above, but without the fallback options, building with `nproc` instead of a static 8 threads, and building for the native architecture.

This supports running as a limited user (not a huge deal) and means we don't have to `pushd` to the run directory in a wrapper script (and therefore we can use relative paths).

```
jeff@desktop:/tmp$ ls -l hash pwlist.txt 
-rw-rw-r-- 1 jeff jeff   686 May  2 11:36 hash
-rw-rw-r-- 1 jeff jeff 10498 May  2 11:41 pwlist.txt
jeff@desktop:/tmp$ john hash -w:pwlist.txt
john: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by john)
Warning: detected hash type "netntlmv2", but the string is also recognized as "ntlmv2-opencl"
Use the "--format=ntlmv2-opencl" option to force loading these as that type instead
Using default input encoding: UTF-8
Loaded 1 password hash (netntlmv2, NTLMv2 C/R [MD4 HMAC-MD5 32/64])
Will run 32 OpenMP threads
Press 'q' or Ctrl-C to abort, almost any other key for status
<redacted>          (Administrator)
1g 0:00:00:00 DONE (2017-05-02 11:41) 50.00g/s 50000p/s 50000c/s 50000C/s arizonA1..28961020
Use the "--show" option to display all of the cracked passwords reliably
Session completed
```

**Comment by BustedSec** [comment]
Would you mind if I incorporated your fix into a pull request?

**Comment by jeffmcjunkin** [comment]
Not at all! I probably should've just done that in the beginning.

I figured it was too large a change to presumptuously send a PR ;)

**Comment by jeffmcjunkin** [comment]
@BustedSec did you have a chance to put together a PR for this issue? I have a downstream project that is affected, currently.

**Comment by BustedSec** [comment]
sorry, got distracted. Will work on this in the morning.

**Comment by jeffmcjunkin** [comment]
@BustedSec I'm having troubles with nested quotes. The system-wide install script uses both single and double quotes.

Contrary to our other conversation, I'd appreciate if you had a working PR for this issue. I might chime in about fallback binaries after I see how you solve the nested quotation problem :)

**Comment by BustedSec** [comment]
yeah I've been dealing with the same issue - still working on it

**Comment by jeffmcjunkin** [comment]
@BustedSec apparently it's entirely valid to skip wrapping `AFTER_COMMANDS` in quotes, code-wise. See https://github.com/trustedsec/ptf/blob/master/src/core.py#L213. This worked fine in my local testing. 

Given this, would a PR where `AFTER_COMMANDS` isn't wrapped in quotes be acceptable?

**Comment by BustedSec** [comment]
As long as it works I don't see why not. I'm just a contributor to the project, I don't have final say over pull requests but if it works I don't see why the TrustedSec guys wouldn't pull it.
