### ISSUE TITLE
Getting Error when running ptf script

### ISSUE THREAD

**Issue by blkv0lk** [trustedsec/ptf#308]
[!] [!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.
[!] [!] It's not possible its due to my coding skillz, it must be you? :-)
[!] [!] Printing that error. Get that error. You get it: inconsistent use of tabs and spaces in indentation (framework.py, line 431)

I get the above error when attempting to run the ptf script. ive got my editor to convert tabs into spaces as sometimes that may be the case but am still experiencing the same error. 
I am running manjaro arch.

**Comment by trustedsec** [comment]
Thanks for the PR, should be fixed now.
