### ISSUE TITLE
HowTo: Uninstall/Remove PTF?

### ISSUE THREAD

**Issue by komodev** [trustedsec/ptf#309]
Can anyone help me out to completely remove the PTF, lot's of configuration on my apache server is broken after installation, ptf works fine, updated all modules and tested it but now I need to roll-back my apache2 state so if anyone can explain shortly how to completely remove it, would be gratefull.

cheers
komodo

**Comment by trustedsec** [comment]
Just delete the /pentest directory and the directory which installs PTF.

**Comment by PLEASEFORGETME2** [comment]
I did that but now when I open a terminal, there is
`root@docker-ptf:`
instead of
`root@kali:`
I removed ptf... I don't know how to change this ! 
pls help
thanks

**Comment by vonvy** [comment]
@PLEASEFORGETME2 

I renamed the /etc/hostname file to change it. It has yet to change from *@docker-ptf


I had admin rights to change. Let me try a couple more things to see if I can get it to work.

**Comment by akshat12233** [comment]
> I did that but now when I open a terminal, there is
> `root@docker-ptf:`
> instead of
> `root@kali:`
> I removed ptf, and in .bashrc file there is no ptf at the ps1...
> I don't know how to change this !
> okay actually I just changed it, it's in /ect/hostname...
> I let my comment in case somebody else could use it
> thanks

wait a minut u just changed the host name in that file or changed the whole file with new hostname please reply

**Comment by T3nsh0** [comment]
It was a long time ago now but I think I just changed the name without
removing the whole file

Le mar. 7 avr. 2020 à 15:59, akshat12233 <notifications@github.com> a
écrit :

**Comment by akshat12233** [comment]
Thankyou bro i just also did thankyou

**Comment by richard-clifford** [comment]
I've had the exact same issue today. Completely fubard my ubuntu laptop

**Comment by bibush0695** [comment]
how did you delete ptf ? reply pls

**Comment by akshat12233** [comment]
fuck you asshole

**Comment by bibush0695** [comment]
are you talking to me ?

**Comment by akshat12233** [comment]
y e s

**Comment by jbhntr861** [comment]
lol wtf. why did yall delete ptf?
