### ISSUE TITLE
Gobuster - Cannot download, $GOPATH not set

### ISSUE THREAD

**Issue by StuartWinterTear** [trustedsec/ptf#312]
I've been trying for a couple of days to get Gobuster to work on Ubuntu 16 Server & Desktop. I have the same problem each time:

If you run Gobuster in ptf it simply says twice:

"Cannot download, $GOPATH not set"

There's lots of conflicting advise out there, but nothing has worked for me.

Any help. greatly appreciated. I'm totally baffled.

Thanks

Stuart

**Comment by BustedSec** [comment]
Hmm, seems like GO is missing a few environmental variables -  maybe try this :

```
mkdir $HOME/.go
echo export $GOPATH="$HOME/.go/ >> ~/.bashrc && echo export PATH=$PATH:$GOPATH/bin >> ~/bashrc
```
this code should append the required path variables to the end of your .bashrc file - this should work assuming your are using bash as your default login shell. If you are using zsh or something else the same logic should work with .zshrc

you will probably need to close the terminal emulator and reopen it again after doing this unless your re-source your .bashrc
