### ISSUE TITLE
hydra.py: libncp-dev no longer accessible

### ISSUE THREAD

**Issue by jeffmcjunkin** [trustedsec/ptf#314]
https://github.com/trustedsec/ptf/blob/d55f9b51d1adc893be11e0e9d6fec5de5defca53/modules/vulnerability-analysis/hydra.py#L23

Neither Debian (https://packages.debian.org/search?keywords=libncp-dev) nor Ubuntu (https://packages.ubuntu.com/search?keywords=libncp-dev&searchon=names&section=all) have supported releases with libncp-dev. 

Maybe we should just remove it from the pre-requisites?

**Comment by BustedSec** [comment]
@jeffmcjunkin is correct - tested this out - no need for the dependency anymore. Works fine without it on ub16.04 and ub17.04. Recommend merging his pull request.
