### ISSUE TITLE
architecture arm64

### ISSUE THREAD

**Issue by lacroutelacroute** [trustedsec/ptf#326]
When installing ptf on roote phones with kali linux
ptf automatically adds the i386 architecture for dpkg
Which is not the right idea
Let things be in the state would be the best thing
Only arm64 architecture for rooted phone

**Comment by BustedSec** [comment]
try commenting out lines 395-400 of ptf/framework.py and let me know if that fixes your issue

**Comment by lacroutelacroute** [comment]
i have commented 395-400 out lines of src/framework.py

not work
android@localhost:/opt/ptf/ptf$ sudo ./ptf          
[*] You can always type ./ptf --no-network-connection to skip the Internet check..
[*] Checking for an Internet connection...
[*] Trying to update myself first.. Then starting framework.
Already up-to-date.
[!] [!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.
[!] [!] It's not possible its due to my coding skillz, it must be you? :-)
[!] [!] Printing that error. Get that error. You get it: unindent does not match any outer indentation level (framework.py, line 410)
android@localhost:/opt/ptf/ptf$

**Comment by BustedSec** [comment]
ok, how about just commenting out lines 

41-43

if profile_os() == "DEBIAN":
    subprocess.Popen("sudo dpkg --add-architecture i386",
                     stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)

so it becomes

#if profile_os() == "DEBIAN":
#   subprocess.Popen("sudo dpkg --add-architecture i386",
#                     stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)

**Comment by lacroutelacroute** [comment]
I did differently
no comment just change architecture 
41-43
if profile_os() == "DEBIAN":
subprocess.Popen("sudo dpkg --add-architecture  armhf",
stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)

**Comment by lacroutelacroute** [comment]
test again work fine

**Comment by BustedSec** [comment]
ok great - you mind closing out the issue?
