### ISSUE TITLE
Clarification Needed: install_update_all

### ISSUE THREAD

**Issue by CreativeWolf** [trustedsec/ptf#328]
Hi,

Firstly, Thank you for putting this together :)

Issue / Clarification Needed: 

Using `install_update_all` seems to be reinstalling everything - I'm trying to understand if this is the intended behaviour as I'm trying to only update. Noticed this happen twice when trying to only update and not reinstall. Should I be using `update_installed` instead?

OS Info: Ubuntu 16.04.1

Thanks

**Comment by CreativeWolf** [comment]
Update:

After running `install_update_all` I wanted to check running `update_installed` and it ended up installing a whole lot again.

A screen grab for AutoIt - Previously installed but going through the process again

![ptf-update_installed](https://user-images.githubusercontent.com/5315780/27500647-fc2cbd6a-5886-11e7-84f0-57954110c50c.png)

The same case for Veil Framework, MSF, Python for Windows et al.

**Comment by BustedSec** [comment]
this is the way it is supposed to work.
