### ISSUE TITLE
/usr/local/bin/theHarvester: 4: /usr/local/bin/theHarvester: ./theHarvester.py: Permission denied

### ISSUE THREAD

**Issue by sidahmed-malaoui** [trustedsec/ptf#329]
When trying to launch `theHarvester` using the command line `theHarvester`, I am getting this error : 

>/usr/local/bin/theHarvester: 4: /usr/local/bin/theHarvester: ./theHarvester.py: Permission denied

The problem is with the third line on the launching script (`/usr/local/bin/theHarvester`) : 
```bash
#!/bin/sh
cd /pentest/intelligence-gathering/theharvester/
find theHarvester.py -executable || chmod +x theHarvester.py
./theHarvester.py $*
```

`find` is having a weird behavior. I moved to the directory `/pentest/intelligence-gathering/theharvester/`, and : 
```
ls -l theHarvester.py
> -rw-r--r-- 1 root root 16665 juil. 10 10:31 theHarvester.py
```

We see that the file isn't executable, so I executed the command `find theHarvester.py -executable || chmod +x theHarvester.py` as root and listed again : 
```
find theHarvester.py -executable || chmod +x theHarvester.py
ls -l theHarvester.py
> -rw-r--r-- 1 root root 16665 juil. 10 10:31 theHarvester.py
```

I even tried this `find theHarvester.py -executable || echo "hello"`, and it didn't echo anything.

**NOTE** I know that it is easy to solve this problem as a user, you just have to manually do a `chmod +x /pentest/intelligence-gathering/theharvester/theHarvester.py`. But I thought it would be better to declare it here to solve it the right way and definitely.

**Comment by sidahmed-malaoui** [comment]
Just an additional information. This problem isn't only `theHarvester` script problem, a lot of other scripts are behaving in the same way (like `sparta`).

**Comment by trustedsec** [comment]
This should be addressed with the latest PR - marked +x instead of +e, let me know if this persists

**Comment by BustedSec** [comment]
@trustedsec issue seems to still be happening with nikto and a few other tools - might be due to having them already installed - even after update-upgrade-all same thing - gonna wipe /pentest/ and rebuild for testing

**Comment by BustedSec** [comment]
on a fresh setup with newly cloned ptf same issue is present in theHarvester and nikto. Chmod +x fixes it

**Comment by sidahmed-malaoui** [comment]
I guess that the problem is in `find theHarvester.py -executable` . It doesn't return false is the file is not executable, so the second command `chmod +x` is never executed.

**Comment by trustedsec** [comment]
This has been resolved, closing.
