### ISSUE TITLE
Can you add a way to uninstall modules ?

### ISSUE THREAD

**Issue by sidahmed-malaoui** [trustedsec/ptf#334]
I don't know if I'm allowed to ask for this kind of things ! But it would be cool if we can uninstall modules from `ptf`.

I know that we can manually remove the directory of a module inside the directory `/pentest/dir_of_module`, but this doesn't completely remove a module. Because as you know, some modules add extra files to the directories outside the `/pentest` directory (like in the directory `/usr/local/bin`, or some libraries may be).

**Comment by BustedSec** [comment]
Yes, this is something we can work on. Doing this will take a long time though, as it requires going through each module and finding all directories it creates. With tools that create databases it adds another level of complexity along with those that make custom web server changes like mana and karma. I will work on this after defcon. Good idea! - Always feel free to make suggestions. We are all volunteers here trying to make this thing better.

**Comment by sidahmed-malaoui** [comment]
Thanks, you are really wonderful devs.

Nothing urgent, but it is nice to keep this idea in mind. You can work on this gradually, I'm sure a lot of people would like to help (I'm one of them hihi).

**Comment by trietptm** [comment]
I am in need of a way to uninstall modules too.
