### ISSUE TITLE
/tmp folder used during "install all" fills small internal drive. Redirect?

### ISSUE THREAD

**Issue by prometx** [trustedsec/ptf#338]
Hi, 

I am trying to install all tools onto a chromebook converted to a linux install. I was happy to see that ptf.config allows designating a directory for the installation of the packages, which I pointed to my 128G sdcard. 

I had assumed this would direct all the file operations to take place in that directory. The install failed actually though, due to its having filled the /tmp folder with its various package operations, on the much smaller ~3G remaining on the internal MMC drive.

`cpyrit/_cpyrit_cpu.c:2577:1: fatal error: error writing to /tmp/ccZgZbdz.s: No space left on device
 }
 ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
[*] Completed running after commands routine..
[!] [!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.
[!] [!] It's not possible its due to my coding skillz, it must be you? :-)
[!] [!] Printing that error. Get that error. You get it: [Errno 28] No space left on device
`

Is there a way to direct ptf to also do these /tmp operations on the sdcard?

Thanks for your great work on this package, btw. Awesome...

Best,

**Comment by jeffmcjunkin** [comment]
Despite appearances, this error is from pyrit, not ptf itself -- ptf is just passing on the error to the user. ptf doesn't have any control over what folders its utilities are using.

If it were me, I'd remove your existing /tmp contents and mount your SD card to that directory.

**Comment by prometx** [comment]
Hi Jeff,

Roger that, will do. Thanks very much for taking the time to reply.
