### ISSUE TITLE
Dirb module not installing

### ISSUE THREAD

**Issue by SPSBB** [trustedsec/ptf#341]
The Dirb module seems to fail when issuing the install command. A quick google/Github search indicates the Dir repor (https://github.com/seifreed/dirb.git) is no longer available. The repo page present a 404 'Not found' error.

Is there a work around for this ?

Cheers.

Install output:

ptf> search dirb
[*] Search results below:
modules/intelligence-gathering/dirb
ptf> use modules/intelligence-gathering/dirb
ptf:(modules/intelligence-gathering/dirb)>install

Module Author:         Brice Samulenok (BriceTheGrey)
Module Description:    This module will install/update dirb - A URL Bruteforcer
-------------------------------------------------------------------------------------
INSTALL_TYPE:           GIT
REPOSITORY_LOCATION:    https://github.com/seifreed/dirb.git
INSTALL_LOCATION:       /pentest/intelligence-gathering/dirb/
-------------------------------------------------------------------------------------
[*] Preparing dependencies for module: modules/intelligence-gathering/dirb
Reading package lists...
Building dependency tree...
Reading state information...
git is already the newest version (1:2.7.4-0ubuntu1.2).
0 to upgrade, 0 to newly install, 0 to remove and 32 not to upgrade.
Reading package lists...
Building dependency tree...
Reading state information...
libcurl4-gnutls-dev is already the newest version (7.47.0-1ubuntu2.2).
0 to upgrade, 0 to newly install, 0 to remove and 32 not to upgrade.
[*] Pre-reqs for modules/intelligence-gathering/dirb have been installed.
[*] Making the appropriate directory structure first
[*] GIT was the selected method for installation... Using GIT to install.
[*] Installing now.. be patient...
Username for 'https://github.com': *********
Password for 'https://*********@github.com': 
[*] Finished Installing! Enjoy the tool located under: /pentest/intelligence-gathering/dirb/
[*] Running after commands for post installation requirements.
[*] Sending after command: cd /pentest/intelligence-gathering/dirb/
[*] Sending after command: ./configure
/bin/sh: 1: ./configure: not found
[*] Sending after command: make
make: *** No targets specified and no makefile found. Stop.
[*] Sending after command: mkdir /usr/share/dirb
mkdir: cannot create directory ‘/usr/share/dirb’: File exists
[*] Sending after command:  mkdir /usr/share/dirb/wordlists
mkdir: cannot create directory ‘/usr/share/dirb/wordlists’: File exists
[*] Sending after command:  cp -r wordlists /usr/share/dirb/
cp: cannot stat 'wordlists': No such file or directory
[*] Completed running after commands routine..
[*] Running updatedb to tidy everything up.

**Comment by trustedsec** [comment]
Since its no longer there/supported - going to remove until I figure out a new location/workaround.
