### ISSUE TITLE
OneSixtOne.py Not installing

### ISSUE THREAD

**Issue by SPSBB** [trustedsec/ptf#342]
The OneSixtyOne.py module seems to fail when issuing the install command. A quick google for the portculis DL page repo confirms the package (https://labs.portcullis.co.uk/download/onesixtyone-0.7.tar.gz) is still available. I can DL this package directly from the portcullis website but.

Is there a work around for this ?

Cheers.

Install Output:

-------------------------------------------------------------------------------------
[*] Preparing dependencies for module: modules/intelligence-gathering/onesixtyone
Reading package lists...
Building dependency tree...
Reading state information...
git is already the newest version (1:2.7.4-0ubuntu1.2).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
Reading package lists...
Building dependency tree...
Reading state information...
gcc is already the newest version (4:5.3.1-1ubuntu1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
Reading package lists...
Building dependency tree...
Reading state information...
make is already the newest version (4.1-6).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
[*] Pre-reqs for modules/intelligence-gathering/onesixtyone have been installed.
[*] Making the appropriate directory structure first
[*] FILE was the selected method for installation... Using curl -o to install.
[*] Finished Installing! Enjoy the tool located under: /pentest/intelligence-gathering/onesixtyone/
[*] Running after commands for post installation requirements.
[*] Sending after command: cd /pentest/intelligence-gathering/onesixtyone/
[*] Sending after command: tar xzf onesixtyone-0.7.tar.gz
tar (child): onesixtyone-0.7.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
[*] Sending after command:  rm onesixtyone-0.7.tar.gz
rm: cannot remove 'onesixtyone-0.7.tar.gz': No such file or directory
[*] Sending after command:  cp onesixtyone-0.7/* /pentest/intelligence-gathering/onesixtyone/
cp: cannot stat 'onesixtyone-0.7/*': No such file or directory
[*] Sending after command: make -j4
make: *** No targets specified and no makefile found. Stop.
[*] Sending after command: make install
make: *** No rule to make target 'install'. Stop.
[*] Completed running after commands routine..
[*] Running updatedb to tidy everything up.

**Comment by jeffmcjunkin** [comment]
Using `sysdig` as follows it seems like, at least for me on Ubuntu 16.04 x64, `curl` is failing due to an untrusted certificate:

```
jeff@desktop:~/dev/ptf$ sudo sysdig -pc -c spy_users

jeff@desktop:~$ sudo ./ptf # in other terminal window
ptf:(modules/intelligence-gathering/onesixtyone)>run
[...other cruft skipped...]
    26828 14:23:46 root@host) curl -A Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.112 Safari/534.30 -o /pentest/intelligence-gathering/onesixtyone/onesixtyone-0.7.tar.gz https://labs.portcullis.co.uk/download/onesixtyone-0.7.tar.gz
```

Running the `curl` command by itself I see as follows:
```
jeff@desktop:~/dev/ptf$ curl -A 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.112 Safari/534.30' -o /pentest/intelligence-gathering/onesixtyone/onesixtyone-0.7.tar.gz https://labs.portcullis.co.uk/download/onesixtyone-0.7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

In Firefox I do see they're not including the whole certificate chain -- more info from SSL Labs: https://www.ssllabs.com/ssltest/analyze.html?d=labs.portcullis.co.uk&latest

I wouldn't recommend just adding `-k` to `curl`, but I'm not sure what a reasonable workaround is otherwise.

**Comment by trustedsec** [comment]
Added -k to curl, will push out in 1.16 soon
