### ISSUE TITLE
Feature Request - Error codes for modules that don't install properly

### ISSUE THREAD

**Issue by cathedrall** [trustedsec/ptf#349]
For the update_install all module, it'd be nice to have some sort of error code tracking.
Lots of these modules aren't installing correctly as I view the install progress but it scrolls by so fast it's hard to capture all the output for troubleshooting. 
I'm sure lots of these are dependency issues, as this is a fresh install of arch that I'm currently installing on. It's more a feature request than a bug.

Great idea on this though, and look forward to future improvements.

**Comment by delirious-lettuce** [comment]
@cathedrall ,

Although I can't say for sure that they are all fixed (as there could be other issues), I just sent PR #360 which fixes the misplaced quotes in a number of files that were causing each of them to throw a `SyntaxError`.
