### ISSUE TITLE
Same Issues as "issue 198" WhatWeb broken again.

### ISSUE THREAD

**Issue by Seceventspen** [trustedsec/ptf#350]
Hi guys,

Seems as though the OP's issue (issue 198) is back again!! Whatweb is no longer working with Ubuntu 16.04LTS and ruby package:

$ ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

I'm getting "./whatweb: /usr/lib/ruby/vendor_ruby/rchardet/universaldetector.rb:39: invalid multibyte escape: /[\x80-\xFF]/ (SyntaxError)" while trying to run it now.

Tried the previous fix mentioned above, appending the 'n' and Whatweb does run but spits out an additonal error before returning the target info.

I've edited /usr/lib/ruby/vendor_ruby/rchardet/universaldetector.rb and placed the 'n' at the end of the following lines:

  @_highBitDetector = /[\x80-\xFF]/n
  @_escDetector = /(\033|\~\{)/n

Then rerun Whatweb with a target domain specified and get the following error line but with target data returned:

---[snip]---
$ whatweb m*************.com
/usr/share/whatweb/plugins/wordpress.rb:436: warning: key "2.7-beta1" is duplicated and overwritten on line 453
---target whatweb data removed for privacy reasons---

This error message appears regardless of domain or IP used, though now whatweb starts and functions.

**Comment by trustedsec** [comment]
Hmmm, I can't seem to reproduce this one, on a fresh install:

root@stronghold:/pentest/vulnerability-analysis/whatweb# ./whatweb

.$$$     $.                                   .$$$     $.         
$$$$     $$. .$$$  $$$ .$$$$$$.  .$$$$$$$$$$. $$$$     $$. .$$$$$$$. .$$$$$$. 
$ $$     $$$ $ $$  $$$ $ $$$$$$. $$$$$ $$$$$$ $ $$     $$$ $ $$   $$ $ $$$$$$.
$ `$     $$$ $ `$  $$$ $ `$  $$$ $$' $ `$ `$$ $ `$     $$$ $ `$      $ `$  $$$'
$. $     $$$ $. $$$$$$ $. $$$$$$ `$  $. $  :' $. $     $$$ $. $$$$   $. $$$$$.
$::$  .  $$$ $::$  $$$ $::$  $$$     $::$     $::$  .  $$$ $::$      $::$  $$$$
$;;$ $$$ $$$ $;;$  $$$ $;;$  $$$     $;;$     $;;$ $$$ $$$ $;;$      $;;$  $$$$
$$$$$$ $$$$$ $$$$  $$$ $$$$  $$$     $$$$     $$$$$$ $$$$$ $$$$$$$$$ $$$$$$$$$'

WhatWeb - Next generation web scanner version 0.4.8-dev.
Developed by Andrew Horton aka urbanadventurer and Brendan Coles.
Homepage: http://www.morningstarsecurity.com/research/whatweb

Usage: whatweb [options] <URLs>

TARGET SELECTION:
  <TARGETs>			Enter URLs, hostnames, IP adddresses, or 
  				nmap-format IP ranges.
  --input-file=FILE, -i		Read targets from a file.

AGGRESSION:
  --aggression, -a=LEVEL	Set the aggression level. Default: 1.
  1. Stealthy			Makes one HTTP request per target and also 
  				follows redirects.
  3. Aggressive			If a level 1 plugin is matched, additional
  				requests will be made.

PLUGINS:
  --list-plugins, -l		List all plugins.
  --info-plugins, -I=[SEARCH]	List all plugins with detailed information.
				Optionally search with a keyword.
  --search-plugins=STRING	Search plugins for a keyword.
  --grep, -g=STRING		Search for STRING in HTTP responses. Reports
				with a plugin named Grep.
OUTPUT:
  --verbose, -v			Verbose output includes plugin descriptions. 
				Use twice for debugging.
  --colour,--color=WHEN		control whether colour is used. WHEN may be 
				`never', `always', or `auto'.
 
HELP & MISCELLANEOUS:
  --short-help			This short usage help.
  --help, -h			Complete usage help.

EXAMPLE USAGE:
* Scan example.com.
  ./whatweb example.com
* Scan reddit.com slashdot.org with verbose plugin descriptions.
  ./whatweb -v reddit.com slashdot.org
* An aggressive scan of wired.com detects the exact version of WordPress.
  ./whatweb -a 3 www.wired.com
* Scan the local network quickly and suppress errors.
  whatweb --no-errors 192.168.0.0/24
* Scan the local network for HTTPS websites.
  whatweb --no-errors --url-prefix https:// 192.168.0.0/24
* Scan for crossdomain policies in the Alexa Top 1000.
  ./whatweb -i plugin-development/alexa-top-100.txt \
  --url-suffix /crossdomain.xml -p crossdomain_xml

  Note: This is the short usage help. 
  For the complete usage help use -h or --help.

root@stronghold:/pentest/vulnerability-analysis/whatweb# ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by Seceventspen** [comment]
Awesome, thanks for the reply!

So just ran a quick sanity check my end and what web works fine now! Though just to double check i accessed the:

sudo nano /usr/lib/ruby/vendor_ruby/rchardet/universaldetector.rb file again and removed the 'n' from the following lines which i had to add as the work around (mentioned in original post):

@_highBitDetector = /[\x80-\xFF]/n
@_escDetector = /(\033|~{)/n

saved and exited. Re-ran whatweb from both from the tool dir and from a fresh console and now i get the same error again:

:~$ whatweb 
/pentest/vulnerability-analysis/whatweb/whatweb: /usr/lib/ruby/vendor_ruby/rchardet/universaldetector.rb:39: invalid multibyte escape: /[\x80-\xFF]/ (SyntaxError)

If i re-edit the: /usr/lib/ruby/vendor_ruby/rchardet/universaldetector.rb file once more and re-add the 'n' to both lines which give the syntax error, whatweb runs fine ....

Is this an unique bug on Ubuntu 16.04 LTS ???

**Comment by Seceventspen** [comment]
I'll close this issue then as, in at least my case, by making the change to the config file and adding 'n' to the lines mentioned above provides a work around.
