### ISSUE TITLE
modules/av-bypass/veil-framework sees no tools available without running Veil.py

### ISSUE THREAD

**Issue by jeffmcjunkin** [trustedsec/ptf#357]
![image](https://user-images.githubusercontent.com/1383363/33442685-9cd72fca-d5aa-11e7-8bd9-4ccef9580db5.png)

Host is Ubuntu 16.04.4, kernel 4.13.0-17-generic, very fresh install.

The only thing I wasn't sure of was the prompt on my Metasploit installation (https://github.com/Veil-Framework/Veil-Evasion/blob/master/config/update.py#L171). I answered with my path to the ptf-installed `msfvenom` wrapper:
```
jeff@blue:~/dev/ptf$ which msfvenom
/usr/bin/msfvenom
```
I entered `/usr/bin/`, which matched the trailing slash in `update.py` as linked above. 

In troubleshooting the issue just now, it looks like running `/pentest/av-bypass/veil-framework/Veil.py` once fixed it? I see two tools now (Evasion and Ordnance) with 41 payloads for Evasion.

Feel free to close this issue if it was a PEBCAK. My bet is there's some issue with the post-installation commands... maybe we need to call Veil.py directly once?

**Comment by BustedSec** [comment]
if you cat /usr/bin/msfvenom it should tell you the path to the metasploit install directory. That is just a symlink. Once you have the correct install directory rerun the ptf script and give it that as a paramater
