### ISSUE TITLE
empire error doesnt run empire

### ISSUE THREAD

**Issue by dan7ez** [trustedsec/ptf#362]
Hi I installed the pentest framework and then I installed the "empire" module. I think it installs deathstar and empire (latest version)

however i get the following error when i try to run empire:

Traceback (most recent call last):
  File "./empire", line 1381, in <module>
    main = empire.MainMenu(args=args)
  File "/pentest/powershell/empire-ps/lib/common/empire.py", line 79, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable

**Comment by Kaicastledine** [comment]
https://github.com/EmpireProject/Empire/issues/539

Run sudo ./reset.sh

**Comment by dan7ez** [comment]
thanks reset.sh seems to have worked

**Comment by BustedSec** [comment]
can we close this issue?

**Comment by dan7ez** [comment]
Yes, thank you.
