### ISSUE TITLE
force https for git ?

### ISSUE THREAD

**Issue by freeload101** [trustedsec/ptf#370]
So when updating at least dradis it's using plain text git the fix is to force git to use HTTPS but not sure if we make this part of PTF to force https ... ?

`

git config --global url."https://github.com/".insteadOf git@github.com:

git config --global url."https://".insteadOf git://

`

**Comment by trustedsec** [comment]
Thanks, good suggestion. Added, will be in next release.

**Comment by bmedicke** [comment]
Any chance that this could be undone? I prefer to use SSH with a key pair for my repos, and this is a global change that affects ALL repos of a user.
