### ISSUE TITLE
/usr/local/bin/ shortcut script parameter passing issue

### ISSUE THREAD

**Issue by nitefood** [trustedsec/ptf#377]
Hello,

I've noticed that, when passing arguments containing spaces to the tools installed by ptf, they don't work as expected.
I figured this happens because the "shortcut" scripts ptf installs under `/usr/local/bin` use the `$*` variable to pass through every cmdline parameter to the destination script. What happen is that `$*` splits spaced arguments into multiple single arguments (even if you enclose the spaced argument in double quotes), which is not what the user wants when launching the tool in the first place.

This can be fixed using `"$@"` (double quotes included) in the /usr/local/bin script, instead of unquoted `$*`.
Modifying the script to use `"$@"` in my experience (had the necessity to do this with sqlmap, patator and hydra) fixed the problem every time.

Two userful Stack Exchange posts about this behavior:
https://unix.stackexchange.com/a/94200
https://unix.stackexchange.com/a/94135

Thanks for the great tool.

**Comment by trustedsec** [comment]
Thanks! I've added this to the next version, thanks for the submission and looks great.
