### ISSUE TITLE
python dependencies broken after install all tools

### ISSUE THREAD

**Issue by iNoSec** [trustedsec/ptf#378]
Hi all,

After installing all the ptf tools on parrotOS (i like to have all my tools up to date) i have some problem with pip install dependencies. When i want to install some tools like cheat or wpseku or whatever i have some fatal error like `dropbox need requests==2.1.8 and you have ask with 2.5.1`  and an other error on the same tool just after this i have `hackersh need requests>=2.5.2 and you have ask with 2.5.1`
Sorry for the not exact error message but thats the essentials of the message i need to use a lot of different versions of requests for cheat or wpseku and before installed all ptf tools i can do it but while the insatllation something broke that.

**Comment by aoighost** [comment]
I'm having similar issues on Debian Stretch as well.

**Comment by iNoSec** [comment]
tahts because some tools update pip to v10 and thats version is broken... really!!! You must reinstall it on the 9.0.1 and that's work again so some tools broke your debian pip with ptf... like Empire!!! 2 choice, you modify the requirement.txt of empire and some other tools (what tools idk) before use ptf and thtas a pain in the butt or you install only tools you want without ptf and that a pain in the butt too lol

**Comment by trustedsec** [comment]
Thanks for the PR @jeffmcjunkin - awesome stuff. Merged in.
