### ISSUE TITLE
aircrack-ng module installation issue

### ISSUE THREAD

**Issue by DJBoo** [trustedsec/ptf#379]
PTF v.2.0
Debian Ubuntu 16.04.4 LTS
modules/wireless/aircrackng
aircrack script failure leading to ptf script failure.
Issue seen on PTF v1.17 to v2.0

When attempting to install the aircrack-ng module the following is seen during the after_commands section of the ptf script.

[*] Pre-reqs for modules/wireless/aircrackng have been installed.
[*] Making the appropriate directory structure first
[*] GIT was the selected method for installation... Using GIT to install.
[*] Installing now.. be patient...
[*] Finished Installing! Enjoy the tool located under: /pentest/wireless/aircrack-ng/
[*] Running after commands for post installation requirements.
[*] Sending after command: cd /pentest/wireless/aircrack-ng/
[*] Sending after command: make -j4
make: *** No targets specified and no makefile found.  Stop.
[*] Sending after command: make strip
make: *** No rule to make target 'strip'.  Stop.
[*] Sending after command: sed -i 's|http://standards-oui.ieee.org/oui.txt|http://linuxnet.ca/ieee/oui.txt|g' scripts/airodump-ng-oui-update
[*] Sending after command: make install
make: *** No rule to make target 'install'.  Stop.
[*] Sending after command: airodump-ng-oui-update
/bin/sh: 1: airodump-ng-oui-update: not found
[*] Completed running after commands routine..
[*] Running updatedb to tidy everything up.

reviewing and running aircracks autogen.sh script revealed the following:
 
Could not auto-detect 'libtoolize'; please install or specify the 'LIBTOOLIZE' environment variable.

installing the following package (libtool) resolved the issues with autogen.sh and allowed the after_commands to complete successfully finishing the module install.

apt-get install libtool

**Comment by trustedsec** [comment]
Fixed, thanks!

**Comment by jaderoe** [comment]
anyone with a solution for the same error in windows 7??
