### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by wermaxta** [trustedsec/ptf#38]
Hi I have problem with ptf
when i start ptf and type use modules/install_update_all i got this 
[*] You are about to install/update everything. Proceed? [yes/no]: and it type yes and i got this message
[*] Finished updating depends for modules.
[*] Installing and/or updating: modules/vulnerability-analysis/dotdotpwn
[*] Detected installation already. Going to upgrade for you.
[!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.
[!] It's not possible its due to my coding skillz, it must be you? :-)
[!] Printing that error. Get that error. You get it: 'NoneType' object has no attribute 'lower'
How to fix it
my OS is Linux kali 3.18.0-kali3-686-pae #1 SMP Debian 3.18.6-1~kali2
Thank you ;)

**Comment by trustedsec** [comment]
That's my bad, just pushed an update and fixed it. Exit PTF and restart it. Fixed =) Thanks for the report!!
