### ISSUE TITLE
install broken on debian stretch

### ISSUE THREAD

**Issue by aoighost** [trustedsec/ptf#385]
upon running update all, the following output is returned on debian stretch

E: Package 'libmysqlclient-dev' has no installation candidate
E: Package 'swig2.0' has no installation candidate
E: Unable to locate package bully
E: Package 'python-pymssql' has no installation candidate
E: Package 'libmysqlclient-dev' has no installation candidate
E: Unable to locate package libschroedinger-1.0-0
E: Couldn't find any package by glob 'libschroedinger-1.0-0'
E: Couldn't find any package by regex 'libschroedinger-1.0-0'
E: Package 'libreadline6' has no installation candidate
E: Package 'libjpeg-turbo8' has no installation candidate
E: Unable to locate package libjpeg8
E: Unable to locate package libgstreamer-plugins-base0.10-dev
E: Couldn't find any package by glob 'libgstreamer-plugins-base0.10-dev'
E: Couldn't find any package by regex 'libgstreamer-plugins-base0.10-dev'
E: Unable to locate package libgstreamer0.10-dev
E: Couldn't find any package by glob 'libgstreamer0.10-dev'
E: Couldn't find any package by regex 'libgstreamer0.10-dev'
E: Package 'libgnutls-dev' has no installation candidate
E: Unable to locate package urllib3
E: Unable to locate package setuptools
E: Unable to locate package iptools
E: Unable to locate package pydispatcher
E: Unable to locate package flask
E: Unable to locate package macholib
E: Unable to locate package dropbox
E: Unable to locate package pyOpenSSL=
E: Unable to locate package pyinstaller
E: Unable to locate package zlib_wrapper
E: Unable to locate package netifaces
E: Unable to locate package M2Crypto
E: Unable to locate package jinja2
E: Unable to locate package cryptography
E: Unable to locate package pyminifier=

note, backports are installed.

**Comment by jeffmcjunkin** [comment]
Looks like a lot of package names have changed with Debian Stretch:
```
docker run -it debian:stretch /bin/bash
Unable to find image 'debian:stretch' locally
stretch: Pulling from library/debian
cc1a78bfd46b: Pull complete 
Digest: sha256:de3eac83cd481c04c5d6c7344cd7327625a1d8b2540e82a8231b5675cef0ae5f
Status: Downloaded newer image for debian:stretch
root@39abc7bfa16f:/# apt update >/dev/null 2>&1
root@39abc7bfa16f:/# apt search libmysqlclient-dev     
Sorting... Done
Full Text Search... Done
default-libmysqlclient-dev/stable 1.0.2 amd64
  MySQL database development files (metapackage)

root@39abc7bfa16f:/# apt search swig
Sorting... Done
Full Text Search... Done
libmath-gsl-perl/stable 0.39-1 amd64
  interface to the GNU Scientific Library using SWIG

swig/stable 3.0.10-1.1 amd64
  Generate scripting interfaces to C/C++ code

swig-doc/stable 3.0.10-1.1 all
  HTML documentation for SWIG

swig-examples/stable 3.0.10-1.1 all
  Examples for applications of SWIG

swig-sphinxbase/stable 0.8+5prealpha-3 all
  Speech recognition tool - swig helpers

swig3.0/stable 3.0.10-1.1 amd64
  Generate scripting interfaces to C/C++ code

swig3.0-doc/stable 3.0.10-1.1 all
  HTML documentation for SWIG

swig3.0-examples/stable 3.0.10-1.1 all
  Examples for applications of SWIG

valabind/stable 0.10.0-2 amd64
  converts vapi files to SWIG, C++, GIR or GEAR files
```

Some of these packages might have compatible names across multiple Debian releases, others may not.

For now, I'd recommend just documenting that `ptf` is built to work on Debian Jessie and Ubuntu 14.04/16.04, and whichever Fedora releases.

**Comment by elisboa** [comment]
> any updates on this? is it working in debian stretch?

Use qml-module-qtgraphicaleffects instead
