### ISSUE TITLE
faraday

### ISSUE THREAD

**Issue by f-amato** [trustedsec/ptf#399]
Hi there!
Thanks for your excellent project!
I saw that you have our version 2.7, we are going to release 3.0 (beta is released on github) Do you want that we send you a pull request or normally you are the one that update the new editions.
Best

**Comment by trustedsec** [comment]
That would be great, a pull request is the easiest :) Thanks for the heads up!

**Comment by robertofocke** [comment]
step 7- upgrade version 3.0 : https://github.com/robertofocke/ptf/blob/master/Qubes%20And%20Faraday%20Install
