### ISSUE TITLE
clean OSX laptop Unable to detect Internet connection. Needed for PTF.

### ISSUE THREAD

**Issue by s1tl** [trustedsec/ptf#401]
Hi, if I'm missing something obvious please excuse me

On a clean build of 10.13.6 (17G65) I get the following error: 
```
 sudo ./ptf :
[*] You can always type ./ptf --no-network-connection to skip the Internet check..
[*] Checking for an Internet connection...
[!] Unable to detect Internet connection. Needed for PTF.
[!] We will now exit PTF. Launch again when you got a connection.
[!] You can also run ptf with the --no-network-connection argument to bypass the network check.
```

when testing with the python interactive console I see the following error: 
From line 30-48 of the main ptf file
```
>> import sys
>>> import subprocess
>>> import os
>>> import socket
>>> rhost = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
>>> rhost.connect(('google.com', 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 49] Can't assign requested address
```

I have found several mac specific errors related to the error code "socket.error: [Errno 49] Can't assign requested address"

https://github.com/namecoin/nmcontrol/issues/116
https://github.com/dask/distributed/issues/890
https://stackoverflow.com/questions/19798254/cant-assign-requested-address-python-multicasting

But I do not understand the solution enough to implement it please advise on how I can assist with resolving this issue

**Comment by trustedsec** [comment]
Hey there, there isn't OS X support for mac and hasn't been tested. Just different distributions of Linux that are supported. Sorry for that - OS X isn't something we are looking to support at this time.

**Comment by s1tl** [comment]
@trustedsec thanks, sorry for the confusion.
