### ISSUE TITLE
Installation stalls out at knockpy

### ISSUE THREAD

**Issue by blackstaratnight** [trustedsec/ptf#404]
When installing knockpy, the system attempts to read a virustotal API key, stalls out and displays line "knockpy/config.json". Then nothing happens. Please advise.
![knockpy](https://user-images.githubusercontent.com/42153262/43735374-0f4ccbe8-9980-11e8-8c43-8d7ffbbe67df.JPG)

**Comment by titicacakilla** [comment]
I have same problem. Anyway try the following:
press ESC key.
enter :q! (colon+q+!).

**Comment by mustafaqasim** [comment]
> When installing knockpy, the system attempts to read a virustotal API key, stalls out and displays line "knockpy/config.json". Then nothing happens. Please advise.
> ![knockpy](https://user-images.githubusercontent.com/42153262/43735374-0f4ccbe8-9980-11e8-8c43-8d7ffbbe67df.JPG)

It's not a problem. Knockpy supports querying Virustotal and this step opens the config file for you to enter the API keys if you wish to use this feature in Konckpy. You can simply exit the editor without saving the changes and the PTF setup will resume.

**Comment by trustedsec** [comment]
Doesn't appear to be a problem now, and doesn't stall.
