### ISSUE TITLE
gobuster missing 'go build'

### ISSUE THREAD

**Issue by brakesec** [trustedsec/ptf#406]
installed gobuster to run a directory search, but there was no binary for gobuster.

in the gobuster.py script, source is pulled, but no binary is created, and 'gobuster' is supposed to be moved to /usr/local/bin, but as it stands, the Go binary won't be created without 'go build'. I attempted to add that, but I do not have commit perms. I copy/pasted the affected file below:

AUTHOR="Zawadi Done"

DESCRIPTION="This module wil install/update GoBuster"

INSTALL_TYPE="GIT"

REPOSITORY_LOCATION="https://github.com/OJ/gobuster"

INSTALL_LOCATION="gobuster"

DEBIAN="golang"

AFTER_COMMANDS="cd {INSTALL_LOCATION},go get github.com/OJ/gobuster,**go build**,mv ~/go/bin/gobuster /usr/local/bin"

LAUNCHER=""

**Comment by jeffmcjunkin** [comment]
Should be fixed in the above PR.
