### ISSUE TITLE
[feature] Description search should be case-insensitive

### ISSUE THREAD

**Issue by phackt** [trustedsec/ptf#414]
Hello,

First of all thanks for your work. While i was playing with your framework, i noticed that the search command also looks for terms in the description module, but surprisingly in a case sensitive way, as it s not the case for the module name. Just to ask if there is no particular option for that, should be great to make the search case insensitive for every fields.

Thanks,

**Comment by aawheatley** [comment]
Fixed in new version 2.4.1. This can be closed ;)

**Comment by phackt** [comment]
Top thanks @aawheatley !
