### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by aboim2** [trustedsec/ptf#417]
I am trying PTF in Mac OS through terminal.
I just downloaded the repo from github and I stumble in this issue:

[*] You can always type ./ptf --no-network-connection to skip the Internet check..
[*] Checking for an Internet connection...
[!] Unable to detect Internet connection. Needed for PTF.
[!] We will now exit PTF. Launch again when you got a connection.
[!] You can also run ptf with the --no-network-connection argument to bypass the network check

I do have internet connection! I check config file and no network config statement.
There is anyway to let framework where is the network card?

**Comment by trustedsec** [comment]
PTF isn’t designed for OSX. Linux specific
