### ISSUE TITLE
Masscan Install Failed Clang Error

### ISSUE THREAD

**Issue by Knowledge-Wisdom-Understanding** [trustedsec/ptf#422]
clang -g -ggdb    -Wall -O3 -c src/rawsock.c -o tmp/rawsock.o
clang: error: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
clang: error while loading shared libraries: libLLVM-6.0.so.1: failed to map segment from shared object
clang -g -ggdb    -Wall -O3 -c src/scripting-banner.c -o tmp/scripting-banner.o
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang: clang: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.error
: unable to execute command: Killed
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Makefile:97: recipe for target 'tmp/rte-ring.o' failed
make: *** [tmp/rte-ring.o] Error 127
make: *** Waiting for unfinished jobs....
clang: error: clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
unable to execute command: Killed
Thread model: posix
InstalledDir: /usr/bin
clang: clang: note: error: clang frontend command failed due to signal (use -v to see invocation)diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
packet_write_wait: Connection to x.xx.xxx.xxx port xxxx: Broken pipe

**Comment by HackingDave** [comment]
Fixed in the latest.
