### ISSUE TITLE
wpscan install fails - Ubuntu 15.04

### ISSUE THREAD

**Issue by oncee** [trustedsec/ptf#43]
ptf:(modules/vulnerability-analysis/wpscan)>install

Module Author:         Mauro Risonho de Paula Assumpcao (firebits)
Module Description:    This module will install/update wpscan - a black box WP scanner
-------------------------------------------------------------------------------------
INSTALL_TYPE:           GIT
REPOSITORY_LOCATION:    https://github.com/wpscanteam/wpscan/
INSTALL_LOCATION:       /pentest/vulnerability-analysis/wpscan/
-------------------------------------------------------------------------------------
[*] Preparing dependencies for module: modules/vulnerability-analysis/wpscan
Reading package lists... Done
Building dependency tree       
....[*] Sending after command: ruby wpscan.rb --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.8
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[i] Update completed.
[*] Completed running after commands routine..
[!] Warning, module modules/vulnerability-analysis/wpscan was found but contains no LAUNCHER field.
[!] Check the module again for errors and try again.
[!] Module has been removed from the list.
[!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.
[!] It's not possible its due to my coding skillz, it must be you? :-)
[!] Printing that error. Get that error. You get it: argument of type 'NoneType' is not iterable
root@localhost:~/ptf# wpscan
No command 'wpscan' found, did you mean:

**Comment by ethicalhack3r** [comment]
Looks like ```module_parser()``` raises ```print_error("Warning, module %s was found but contains no %s field." % (filename_short,term))`` when a search of the module syntax doesn't return any results - https://github.com/trustedsec/ptf/blob/f35f67aceafb7541445df30f388807f85167db42/src/core.py#L173

It seems that some ```LAUNCHER``` directives were added to a few of the tools but not all - https://github.com/trustedsec/ptf/blob/f35f67aceafb7541445df30f388807f85167db42/readme/CHANGELOG#L12

I think the codebase at the moment is not sure if ```LAUNCHER``` should be a required directive or not for modules.

A temporary fix may be to add ```LAUNCHER="wpscan"``` to the end of the wpscan module file - https://github.com/trustedsec/ptf/blob/master/modules/vulnerability-analysis/wpscan.py

**Comment by trustedsec** [comment]
Fixed, thanks for the report - thought I made it an optional flag but it returned None which borked it up. FIxed =)

**Comment by oncee** [comment]
Thanks Dave.
