### ISSUE TITLE
Bettercap is no longer available in the repository of evilsocket

### ISSUE THREAD

**Issue by sidahmed-malaoui** [trustedsec/ptf#431]
Bettercap official repository has moved from https://github.com/evilsocket/bettercap to https://github.com/bettercap/bettercap , so it's better to change it inside PTF.

**Comment by Zawadidone** [comment]
You can make a pull request?

**Comment by sidahmed-malaoui** [comment]
Yeah of course. You have no contribute instructions on the repository, should I just correct, commit then submit a pull request ?

**Comment by Zawadidone** [comment]
Yes!

**Comment by sidahmed-malaoui** [comment]
I just submitted a pull request. I used the cleanest way I found to install `bettercap`. If there is anything you wan't me to change or fix, contact me.

**Comment by evilsocket** [comment]
why not just downloading the precompiled release ( https://github.com/bettercap/bettercap/releases/download/v2.18/bettercap_linux_amd64_2.18.zip ) ?

**Comment by sidahmed-malaoui** [comment]
I didn't think about that because some tools take a long time to release a version (like volatility for example), and I don't know if it's the case for `bettercap`. That's why I thought manual compilation will be better to get the latest version.

But since you're the author of `bettercap`, you are probably right. I can change it if you and the authors of `ptf` want it.

**Comment by evilsocket** [comment]
oh i see ... well we have at least a new release every 2 weeks on average, but that would mean updating the release URL for ptf too, so i guess that just compiling every time from master is the simplest approach

**Comment by sidahmed-malaoui** [comment]
Thank you @evilsocket

**Comment by Zawadidone** [comment]
Please read the PTF manual (https://github.com/sidahmed-malaoui/ptf/pull/1) succes!

**Comment by edermi** [comment]
Maybe it is possible to use Github's [latest release](https://help.github.com/en/articles/linking-to-releases) feature together with the API to dynamically obtain the download link of the latest release binary and grab that one? There seems to be a good oneliner that probably needs a little adaption [here](https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8#gistcomment-2724872). According to  [this](https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8#gistcomment-2845270) comment, it is also possible to access the latest tagged asset.
