### ISSUE TITLE
wpscan

### ISSUE THREAD

**Issue by i-am4man** [trustedsec/ptf#433]
installing wpscan via ptf is giving me this error. Tried usual apt-get update and reinstalling/updating wpscan from ptf as well.v

root@kali:/pentest/vulnerability-analysis/wpscan# ./wpscan 
Traceback (most recent call last):
ruby: No such file or directory -- /pentest/vulnerability-analysis/wpscan/wpscan.rb (LoadError)
root@kali:/pentest/vulnerability-analysis/wpscan# ruby wpscan
Traceback (most recent call last):
ruby: no Ruby script found in input (LoadError)
root@kali:/pentest/vulnerability-analysis/wpscan# wpscan
Traceback (most recent call last):
ruby: No such file or directory -- /pentest/vulnerability-analysis/wpscan/wpscan.rb (LoadError)

**Comment by predator500** [comment]
Hi, check the wpscan git, check the requirements, and start from /pentest/vulnerability-analysis/wpscan.
If needed reinstall from Wpscan git. OR using the ptf module.
I had the same problem and one of those was the solution.

**Comment by trustedsec** [comment]
Fixed on latest push
