### ISSUE TITLE
Install all stalls out at dnsenum

### ISSUE THREAD

**Issue by sptankard** [trustedsec/ptf#438]
During install all, the installation stalled at dnsenum module with the following line:

```
t/local/back.t ........................... 1/47 Error GETing http://127.0.0.1:36375/: Can't connect to 127.0.0.1:36375 (Connection refused) at t/local/back.t line 53.
```

Ctrl-c was sufficient to skip dnsenum and resume the install for everything else.

**Comment by samuelkneppel** [comment]
FWIW I am experiencing this as well.

**Comment by trustedsec** [comment]
Hmm, can you confirm this is still an issue? I was able to install without issue

**Comment by Michael-Aguilera** [comment]
I found Ctrl+c only cut off the installation for me when I got this error. I had to go to the config file and exclude dnsenum completely from updates and installations. You can follow the steps on the README.md page. Hope this helps.

**Comment by odin2012** [comment]
I can confirm this is still an issue, I attempted a fresh install with the install all options and encountered the same issue. Once I removed dnsenum script I was able to complete the full install.

**Comment by bradgcoza** [comment]
Same issue, removing dnsenum was a workaround for now.

**Comment by HackingDave** [comment]
Fixed in latest
