### ISSUE TITLE
Full installation keeps hanging up in line 52 - error getting http://127.0.0.1:42353

### ISSUE THREAD

**Issue by nukeduke00** [trustedsec/ptf#449]
# === Runtime Requires ===
# 
#     Module                 Want Have
#     --------------------- ----- ----
#     Carp                    any 1.50
#     Getopt::Long            any  2.5
#     HTML::Form             1.00 6.03
#     HTML::HeadParser        any 3.71
#     HTML::TokeParser        any 3.69
#     HTML::TreeBuilder         5 5.07
#     HTTP::Cookies           any 6.04
#     HTTP::Request          1.30 6.18
#     HTTP::Request::Common   any 6.18
#     LWP::UserAgent        5.827 6.36
#     Pod::Usage              any 1.69
#     Scalar::Util           1.14 1.50
#     Tie::RefHash            any 1.39
#     URI::URL                any 5.04
#     URI::file               any 4.21
#     base                    any 2.27
#     strict                  any 1.11
#     warnings                any 1.42
# 
t/00-report-prereqs.t .................... ok   
t/add_header.t ........................... ok   
t/aliases.t .............................. ok   
t/area_link.t ............................ ok   
t/autocheck.t ............................ ok   
t/bad-request.t .......................... ok   
t/clone.t ................................ ok   
t/content.t .............................. ok   
t/cookies.t .............................. # Test server http://127.0.0.1:31037 as PID 195708
t/cookies.t .............................. ok     
t/credentials-api.t ...................... ok   
t/credentials.t .......................... ok     
t/die.t .................................. skipped: Test::Exception required to test die
t/dump.t ................................. ok   
t/field.t ................................ ok   
t/find_frame.t ........................... ok   
t/find_image.t ........................... ok    
t/find_inputs.t .......................... ok     
t/find_link-warnings.t ................... skipped: Test::Warn required to test t/find_link-warnings.t
t/find_link.t ............................ ok     
t/find_link_id.t ......................... ok    
t/form-parsing.t ......................... ok   
t/form_with_fields.t ..................... ok    
t/form_with_fields_passthrough_params.t .. ok    
t/frames.t ............................... ok   
t/history.t .............................. ok    
t/image-new.t ............................ ok     
t/image-parse.t .......................... ok     
t/link-base.t ............................ ok   
t/link-relative.t ........................ ok   
t/link.t ................................. ok     
t/local/back.t ........................... 1/47 Error GETing http://127.0.0.1:42353/: Can't connect to 127.0.0.1:42353 (Connection refused) at t/local/back.t line 53.

**Comment by Jack10o** [comment]
Hi i have same issue did you find a solution?
