### ISSUE TITLE
After install on Zorin OS using the Git Clone method, there is an error that occurs after the network check.

### ISSUE THREAD

**Issue by vonvy** [trustedsec/ptf#453]
I have installed PTF in Ubuntu multiple times. After trying out a new OS, Zorin OS which is based on Ubuntu 18.04 LTS, I have encountered this error. 

`sudo ./ptf
[*] You can always type ./ptf --no-network-connection to skip the Internet check..
[*] Checking for an Internet connection...
[*] Trying to update myself first.. Then starting framework.
fatal: not a git repository (or any of the parent directories): .git
[!] [!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occurred.
[!] [!] It's not possible its due to my coding skillz, it must be you? :-)
[!] [!] Printing that error. Get that error. You get it: No module named pexpect
`

How can I go about fixing this?

**Comment by trustedsec** [comment]
pip install pexpect

**Comment by trustedsec** [comment]
I've just pushed a new release that does a pexpect check.
