### ISSUE TITLE
1/47 Error GETing http://127.0.0.1:42353/: Can't connect to 127.0.0.1:42353 (Connection refused) at t/local/back.t line 53.

### ISSUE THREAD

**Issue by Jack10o** [trustedsec/ptf#456]
Hi can you please tell me how to fix this it's been there for a while now i use your ptf on different kali and parrot still same error is there is a way you can fix it please i like your ptf thanks

**Comment by kom82** [comment]
same issue here...

**Comment by trustedsec** [comment]
Any idea what module this is?

**Comment by ightnapovial** [comment]
Ran into the same issue on raspbian with a pi4. To get past it I had to disable ipv6 and comment out the ipv6 lines from /etc/hosts.

**Comment by kom82** [comment]
GREAT! it works. I confirm that you need to disable IPv6. thanks!!!
