### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by wermaxta** [trustedsec/ptf#47]
Hi my OS is Kali Sana Linux kali 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 when i type use modules/install_update_all i get this 

ptf> use modules/install_update_all
[*] You are about to install/update everything. Proceed? [yes/no]:yes
[*] Auto updating is turned to on, this will install normal package updates for you...
[*] If you want to turn this off, go to the PTF directory and go to config and change AUTO_UPDATE
Hit http://http.kali.org sana InRelease
Hit http://security.kali.org sana/updates InRelease
Hit http://http.kali.org sana/main Sources                                 
Hit http://security.kali.org sana/updates/main Sources                           
Hit http://http.kali.org sana/non-free Sources                                   
Hit http://security.kali.org sana/updates/contrib Sources                        
Hit http://http.kali.org sana/contrib Sources                                    
Hit http://security.kali.org sana/updates/non-free Sources
Hit http://security.kali.org sana/updates/main i386 Packages
Hit http://security.kali.org sana/updates/contrib i386 Packages
Hit http://security.kali.org sana/updates/non-free i386 Packages
Ign http://security.kali.org sana/updates/contrib Translation-en_US
Ign http://security.kali.org sana/updates/contrib Translation-en
Ign http://security.kali.org sana/updates/main Translation-en_US
Ign http://security.kali.org sana/updates/main Translation-en
Ign http://security.kali.org sana/updates/non-free Translation-en_US
Ign http://security.kali.org sana/updates/non-free Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
[*] Finished with normal package updates, moving on to the tools section..
[*] We are going to first install all prereqs using apt before installing..
[*] Cycling through modules and grabbing requirements...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libhttpclient-ruby1.9.1' for regex 'ruby1.9.1'
Note, selecting 'librack-ruby1.9.1' for regex 'ruby1.9.1'
Note, selecting 'liberubis-ruby1.9.1' for regex 'ruby1.9.1'
Note, selecting 'ruby-rack' instead of 'librack-ruby1.9.1'
Note, selecting 'ruby-httpclient' instead of 'libhttpclient-ruby1.9.1'
Note, selecting 'ruby-erubis' instead of 'liberubis-ruby1.9.1'
Package libidn11-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libidn11

Package libkrb5-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  comerr-dev

E: Unable to locate package libnl-dev
E: Unable to locate package ruby-rails-3.2
E: Couldn't find any package by regex 'ruby-rails-3.2'
E: Package 'libkrb5-dev' has no installation candidate
E: Unable to locate package ruby1.9.3
E: Couldn't find any package by regex 'ruby1.9.3'
E: Package 'libidn11-dev' has no installation candidate
E: Unable to locate package zlibc
E: Unable to locate package zlib-bin
E: Package 'libidn11-dev' has no installation candidate

How i can fix it 
Thank you . :)

**Comment by trustedsec** [comment]
The packages for Kali are usually either A. different or B. far behind other packages. I'll take a look at these and see if I can do smart detection on Kali to do different packages.

**Comment by trustedsec** [comment]
This one should still complete as anticipated. Module names are different in Kali than other distributions. Most are already packaged and installed - won't impact installation.
