### ISSUE TITLE
Not work!

### ISSUE THREAD

**Issue by insurgo222** [trustedsec/ptf#475]
for macOS 10.15

[*] Installing and/or updating: modules/update_installed
[*] Installing and/or updating: modules/intelligence-gathering/ipcrawl
[*] Tool not installed yet, will run through install routine
[*] Making the appropriate directory structure first
mkdir: /pentest/intelligence-gathering/ipcrawl/: Read-only file system
[!] [!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occurred.
[!] [!] It's not possible its due to my coding skillz, it must be you? :-)
[!] [!] Printing that error. Get that error. You get it: [Errno 2] No such file or directory: '/pentest/intelligence-gathering/ipcrawl/'

**Comment by skapunker** [comment]
Specifically it's giving the error because the / (root) directory is read-only on macOS 10.15: https://support.apple.com/en-us/HT210650

More importantly however, this tool is not built for macOS so you'll likely run into other issues and I wouldn't recommend using this with macOS.
