### ISSUE TITLE
Installation Error on Docker/Ubuntu

### ISSUE THREAD

**Issue by kahyalar** [trustedsec/ptf#483]
Hi there!

I tried to install PTF on my docker container (ubuntu:latest) and I got this error.

...
/update crunch - wordlist generator
[!] [!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occurred.
[!] [!] It's not possible its due to my coding skillz, it must be you? :-)
[!] [!] Printing that error. Get that error. You get it: 'ascii' codec can't decode byte 0xc5 in position 169: ordinal not in range(128)

**Comment by Linux-sudo** [comment]
I got same error while installing the tools. didn't find anything online for troubleshooting unfortunately.
