### ISSUE TITLE
PACK (Password Analysis and Cracking Toolkit) Dead Link

### ISSUE THREAD

**Issue by SabeBarker** [trustedsec/ptf#486]
Hey :)

Thanks for all your work on PTF. 

There is an issue with:

`modules/password-recovery/password_analysis_and_cracking_kit.py`

The download link `http://thesprawl.org/media/projects/PACK-0.0.4.tar.gz` now redirects to the medium blog `https://medium.com/@iphelix`.

I found a fork of iphelix's github repo that was updated quite recently `https://github.com/Hydraze/pack`

I will check it out and if it is a viable replacement I will submit a pull request with the changes.

Otherwise the module should be removed.

Regards,
sabe

**Comment by jeffmcjunkin** [comment]
FWIW I've used the Hydraze fork before. It functions :)
