### ISSUE TITLE
nmap.py doesn't properly build itself or ncat

### ISSUE THREAD

**Issue by 0xsalt** [trustedsec/ptf#49]
Expected behavior: nmap and ncap will properly build and install when running
ptf> use modules/vulnerability-analysis/nmap
ptf:(modules/vulnerability-analysis/nmap)>install

Actual behavior: 
repository is checked out but nothing is built.

Also adds dependencies to work properly on Ubuntu 14.04-LTS Server

Fixed in github.com/0xsalt/ptf/. Attempting to submit a pull request now ..

**Comment by 0xsalt** [comment]
Cancelled first pull request, branched my forked repo to isolate the nmap bugfix pull. Just learning a git workflow, let me know if you'd like these a different way.

**Comment by trustedsec** [comment]
Thanks, looks good.
