### ISSUE TITLE
Update spiderfoot module

### ISSUE THREAD

**Issue by sidahmed-malaoui** [trustedsec/ptf#499]
Apparently, spiderfoot module is outdated, and the install instructions are outdated.

I can do a pull request to correct this issue if you want.

**Comment by jeffmcjunkin** [comment]
The admins are really, really quick to review and accept PR's. If you can
reliably fix the spiderfoot module, I'd recommend doing so.

**Comment by trustedsec** [comment]
Updated the installation, thanks!
