### ISSUE TITLE
Create type of launcher that CD into the tool directory

### ISSUE THREAD

**Issue by sidahmed-malaoui** [trustedsec/ptf#511]
Some tools (like `beef`), needs you to cd into their directory to launch them, if you launch them outside of their source directory, they wont work.

It will be awesome if `ptf` supports two type of launchers :
  - One that call the tool using absolute path (like the one existing right now in `ptf`).
  - And one that cd into the tool source directly before launching.

I can code this and submit a pull request if the maintainers of the project agree to this idea.

**Comment by HackingDave** [comment]
I'm cool with an idea like that - maybe call it LAUNCHER= and LAUNCHER_FROM_DIR=

**Comment by sidahmed-malaoui** [comment]
@HackingDave Awesome, I'll code it and send a pull request as soon as possible.

**Comment by aawheatley** [comment]
In order for this to work you would have to go through each tool there is and figure out which ones need that function I believe. Have you been able to figure it out @sidahmed-malaoui ?

**Comment by sidahmed-malaoui** [comment]
@aawheatley I don't think I can over all existing tools in `ptf`, that would take me a huge amount of time. I though about implementing this in the framework, then go use it on tools that I know. In the future, any one who needs this future, will find it implemented.

**Comment by sidahmed-malaoui** [comment]
I'm really sorry guys, I should've fixed this issue long time ago. I really didn't find time.
