### ISSUE TITLE
hi friends, why im getting this error on msfconsole

### ISSUE THREAD

**Issue by Puneethchowdary7** [trustedsec/ptf#512]
meterpreter > dump_sms
[*] Fetching 86 sms messages
[-] Error getting messages: Permission denied @ rb_sysopen - sms_dump_20200402173629.txt
meterpreter >

**Comment by HackingDave** [comment]
Not sure, I would check over on the Metasploit forums on that front.

**Comment by ujg7** [comment]
hii im facing the same problem. what is the solution
