### ISSUE TITLE
[TOOL UPGRADE] WIFITE2,OPENVAS

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [trustedsec/ptf#513]
Hello,
Since wifite is not developed anymore can you please add wifite2 to the tool list :
https://github.com/kimocoder/wifite2
Also Openvas is not developed anymore it has been renamed to Greenbone Vulnerability Manager
https://community.greenbone.net/t/about-gvm-architecture/
So please update it to.
PS: I know we can update the list for ourselves but i guess it would be better to ship the latest tools by default

Thank you :)

**Comment by HackingDave** [comment]
Removed wifite and added wifite2 thanks

**Comment by Ashutosh-Kukreti** [comment]
What about OpenVas?
