### ISSUE TITLE
dot11decrypt After Commands Update

### ISSUE THREAD

**Issue by RaiderBW** [trustedsec/ptf#517]
The After Commands in dot11decrypt.py for PTF 2.4 appear to be for a different/older version.  Updating After Commands to the following resolved this:
```
# COMMANDS TO RUN AFTER
AFTER_COMMANDS="cd {INSTALL_LOCATION},mkdir build,cd build,cmake ..,make"
```

**Comment by HackingDave** [comment]
Thanks! Updated it and pushed it out.
