### ISSUE TITLE
unable to run metasploit

### ISSUE THREAD

**Issue by ysivakoti** [trustedsec/ptf#538]
root@parrot]─[~]
└──╼ #msfconsole
Traceback (most recent call last):
	19: from /usr/bin/msfconsole:23:in `<main>'
	18: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
	17: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:55:in `require_environment!'
	16: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
	15: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	14: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `block in require'
	13: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
	12: from /usr/share/metasploit-framework/config/application.rb:11:in `<top (required)>'
	11: from /usr/lib/ruby/2.7.0/bundler.rb:174:in `require'
	10: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
	 9: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
	 8: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
	 7: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
	 6: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
	 5: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:74:in `require'
	 4: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.3.13/lib/sqlite3.rb:4:in `<top (required)>'
	 3: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
	 2: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	 1: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- sqlite3/2.7/sqlite3_native (LoadError)
	20: from /usr/bin/msfconsole:23:in `<main>'
	19: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
	18: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:55:in `require_environment!'
	17: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
	16: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	15: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `block in require'
	14: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
	13: from /usr/share/metasploit-framework/config/application.rb:11:in `<top (required)>'
	12: from /usr/lib/ruby/2.7.0/bundler.rb:174:in `require'
	11: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
	10: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
	 9: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
	 8: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
	 7: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
	 6: from /usr/lib/ruby/2.7.0/bundler/runtime.rb:74:in `require'
	 5: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.3.13/lib/sqlite3.rb:2:in `<top (required)>'
	 4: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.3.13/lib/sqlite3.rb:6:in `rescue in <top (required)>'
	 3: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
	 2: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	 1: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require': /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.3.13/lib/sqlite3/sqlite3_native.so: undefined symbol: sqlite3_column_database_name - /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.3.13/lib/sqlite3/sqlite3_native.so (LoadError)

     Please Help me to find

**Comment by realagentwhite** [comment]
Seems very familiar with the issue on rapid7 (https://github.com/rapid7/metasploit-framework/issues/7036)

**Comment by ysivakoti** [comment]
i tried (rapid7/metasploit-framework#7036) but it didn't work is there any other solution to fix this issue

**Comment by thejoker3000** [comment]
Have you opened an issue with rapid7? You are running msfconsole and not ptf meaning this is an issue for rapid7.

**Comment by BustedSec** [comment]
@ysivakoti What linux distro are you running? It looks like you are in ruby dependency hell. My bet would be something with the openssl library is borked, but I could be wrong.
