### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by Krizsan0596** [trustedsec/ptf#552]
I have cloned the repo, ran bootstrap.sh, and left my computer. When I tried to login it keeps telling me that the password is incorrect, but I know it the right password. The hostname also changed to docker-ptf. Please help

**Comment by thejoker3000** [comment]
If you take a look at the script, on line 9, it has it to set the hostname to **docker-ptf**
`echo "docker-ptf" > /etc/hostname`
For the password and the rest I'm not sure because I haven't ran bootstrap.sh. Did you get any logs from the output?

**Comment by thejoker3000** [comment]
@Krizsan0596 did it work? Have you tried again?

**Comment by Krizsan0596** [comment]
@thejoker3000 Yes. I just reinstalled it and now it works fine

**Comment by thejoker3000** [comment]
@Krizsan0596 so this can be closed?
