### ISSUE TITLE
kali@docker-ptf

### ISSUE THREAD

**Issue by TonicWhisper** [trustedsec/ptf#554]
Hey Guys, 
Please help me to revert kali@docker-ptf back to normal.
I was perfectly building up my Live Kali system, but then this happened.
Please tell me what to do!

**Comment by thejoker3000** [comment]
@TonicWhisper What happened?

**Comment by TonicWhisper** [comment]
> @TonicWhisper What happened?

Hey @thejoker3000 thanks for asking, but as I was so desperate in reverting my system back to normal I backed up my files and reinstalled kali. God bless you brother!

**Comment by TonicWhisper** [comment]
Iam Closing this issue because i got it solved, sorry if i didnt close this issue much earlier, Thanks everyone!
