### ISSUE TITLE
Python3 python-pip cannot be found

### ISSUE THREAD

**Issue by okoester** [trustedsec/ptf#572]
Hi,

I try to install wafw00f via ptf on Ubuntu 20.04
python3-pip is installed:
`# pip -V
pip 21.0.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)`

When sending install command within the module, the following error occurs:
`E: Paket python-pip kann nicht gefunden werden.`

I had tried to reinstall python3 and also upgrade pip version:
`python3 -m pip install --upgrade --force pip`
but I cannot get rid of that error. I'm pretty sure that error is not related to wafw00f but here I can reproduce it whenever I start trying to install.

Any help is appreciated.

Best regards,
Olaf

**Comment by BustedSec** [comment]
I think python-pip uses python2 pip by default so when you're calling pip from the console you're getting the python2 version not the python3 one.  Maybe replace the command with pip3 instead

**Comment by HackingDave** [comment]
Fixed this package, should run fine now. Thanks!
