### ISSUE TITLE
Installing Metasploit

### ISSUE THREAD

**Issue by MunalAdhikari** [trustedsec/ptf#573]
![Screenshot_2021-02-24-20-52-18-02](https://user-images.githubusercontent.com/79589985/109020620-3a6f6f00-76e2-11eb-89a6-3ed656ed9102.jpg)
Can anyone Tellme How To Install Metasploit Without Any Issue.

**Comment by BustedSec** [comment]
What operating system and version are you using?

**Comment by BustedSec** [comment]
Looks like you are trying to install in busybox on a phone. PTF has not been designed for that scenario. You may want to look into nethunter or sherviah

**Comment by MunalAdhikari** [comment]
> Looks like you are trying to install in busybox on a phone. PTF has not been designed for that scenario. You may want to look into nethunter or sherviah

So now how can I install

**Comment by BustedSec** [comment]
use a computer and not a phone.
