### ISSUE TITLE
updatedb takes a long time, potentially runs too often.

### ISSUE THREAD

**Issue by dnx-seek** [trustedsec/ptf#574]
If I install a module ptf runs `updatedb` at the end. Which is fair enough. I'm not sure the exact reason for adding this, but I assume it's useful to have various paths searchable immediately.

So far in my experience updatedb is the slowest part of any install.

If a module has dependencies `updatedb` runs between each installed dependency.

If I run an update, and there is no update, it still runs updatedb.

If I run a multi install, it runs updatedb between each installed tool.

I feel like this could be changed to run less - eg if no update, then don't run updatedb. If a multi-step install, run only at the end. I wonder also if any paths could be prunned (`--prunepaths=)` or if it would be useful to scope to specific paths `--localpaths=`

**Comment by BustedSec** [comment]
This is a really clever find, I'm gonna play around with trying to get that to work. I'm sure Dave could figure it out way faster though.

**Comment by jeffmcjunkin** [comment]
Silly idea, but how about just running `update &` so it doesn't hang up interactive runs and batch runs?

CPU cycles are cheap, but human attention isn't.

**Comment by thejoker3000** [comment]
I've never experienced slowness when updatedb runs.
