### ISSUE TITLE
How can I contribute

### ISSUE THREAD

**Issue by hamzah-sajid-code** [trustedsec/ptf#590]
Hello,
I love this project and I want to contribute in this project
I know Intermediate Python 3 Programming

**Comment by Juliopeirir** [comment]
Muito bom

**Comment by MYavuzYAGIS** [comment]
> Hello, I love this project and I want to contribute in this project I know Intermediate Python 3 Programming


Check the codebase, find a need (more than a typo fix), fork the project, play around, test, and implement it.

Start thinking about what you need more when you use it. Implement this "more"
