### ISSUE TITLE
Not sure where to look for answer, but-

### ISSUE THREAD

**Issue by DanMeadWasTaken** [trustedsec/ptf#591]
So, i'm trying to run lynis in ptf
and it's spitting out this error, this being after i set it up to launch using the command

\nFatal error: can't find include directory\nMake sure to execute Lynis from untarred directory or check your installation.%

**Comment by th3joker3000** [comment]
in the PTF directory from the git download, there is a ptf-output.log file. Does it show any errors?

**Comment by th3joker3000** [comment]
@DanMeadWasTaken ^^^

**Comment by DanMeadWasTaken** [comment]
Well, i ended up stopping using ptf- but from what i remember, it turned out that if i went into root, it'd allow me to run lynis- this was the same for any other program as well running within ptf. Which was a security concern for me, as i didn't want to be running these programs from root.
