### ISSUE TITLE
Depreciate Sparta for Legion

### ISSUE THREAD

**Issue by BustedSec** [trustedsec/ptf#594]
We might want to swap out Sparta for Legion over at https://github.com/GoVanguard/legion.git
it's refactored to use python 3 and has a much more active dev team, and has regular releases. Kali already made the change back in 2020.1. last release for  Sparta was back in 2019, Legion was 2 weeks ago. 

Same familiar UI. 

it is easily installed like so. 
git clone https://github.com/GoVanguard/legion.git
cd legion
sudo chmod +x startLegion.sh
sudo ./startLegion.sh

**Comment by HackingDave** [comment]
Thanks! Pushed release out in 2.7 which removes Sparta for Legion. Thanks!
