### ISSUE TITLE
seclist: Broken `cp` command after install

### ISSUE THREAD

**Issue by jeffmcjunkin** [trustedsec/ptf#616]
```
[*] Pre-reqs for modules/password-recovery/seclist have been installed.
[*] Making the appropriate directory structure first
[*] GIT was the selected method for installation... Using GIT to install.
[*] Installing now.. be patient...
[*] Finished Installing! Enjoy the tool located under: /pentest/password-recovery/dictionary/
[*] Running after commands for post installation requirements.
[*] Sending after command: cd /pentest/password-recovery/dictionary/
[*] Sending after command:  cd ..
[*] Sending after command: if [ -d '/usr/share/wordlists/' ]; then cp -r SecLists/ /usr/share/wordlists/; fi;
cp: cannot stat 'SecLists/': No such file or directory
```

Ties back to https://github.com/trustedsec/ptf/blob/master/modules/password-recovery/seclist.py#L26, since the directory structure looks different now:

```
# ls -al
total 144
drwxr-xr-x 14 root root  4096 Apr 18 01:20 .
drwxr-xr-x  3 root root  4096 Apr 18 01:19 ..
drwxr-xr-x  4 root root  4096 Apr 18 01:20 .bin
-rw-r--r--  1 root root   897 Apr 18 01:20 CONTRIBUTING.md
-rw-r--r--  1 root root 39097 Apr 18 01:20 CONTRIBUTORS.md
drwxr-xr-x  9 root root  4096 Apr 18 01:20 Discovery
drwxr-xr-x 10 root root  4096 Apr 18 01:20 Fuzzing
drwxr-xr-x  8 root root  4096 Apr 18 01:20 .git
-rw-r--r--  1 root root    47 Apr 18 01:20 .gitattributes
drwxr-xr-x  5 root root  4096 Apr 18 01:20 .github
-rw-r--r--  1 root root    51 Apr 18 01:20 .gitignore
drwxr-xr-x  2 root root  4096 Apr 18 01:20 IOCs
-rw-r--r--  1 root root  1072 Apr 18 01:20 LICENSE
drwxr-xr-x  9 root root  4096 Apr 18 01:20 Miscellaneous
drwxr-xr-x 17 root root  4096 Apr 18 01:20 Passwords
drwxr-xr-x  3 root root  4096 Apr 18 01:20 Pattern-Matching
drwxr-xr-x  8 root root  4096 Apr 18 01:20 Payloads
-rw-r--r--  1 root root  2425 Apr 18 01:20 README.md
-rw-r--r--  1 root root 25353 Apr 18 01:20 SecLists.png
drwxr-xr-x  4 root root  4096 Apr 18 01:20 Usernames
drwxr-xr-x 10 root root  4096 Apr 18 01:20 Web-Shells
```

**Comment by snstgithub** [comment]
> ```
> [*] Pre-reqs for modules/password-recovery/seclist have been installed.
> [*] Making the appropriate directory structure first
> [*] GIT was the selected method for installation... Using GIT to install.
> [*] Installing now.. be patient...
> [*] Finished Installing! Enjoy the tool located under: /pentest/password-recovery/dictionary/
> [*] Running after commands for post installation requirements.
> [*] Sending after command: cd /pentest/password-recovery/dictionary/
> [*] Sending after command:  cd ..
> [*] Sending after command: if [ -d '/usr/share/wordlists/' ]; then cp -r SecLists/ /usr/share/wordlists/; fi;
> cp: cannot stat 'SecLists/': No such file or directory
> ```
> 
> Ties back to https://github.com/trustedsec/ptf/blob/master/modules/password-recovery/seclist.py#L26, since the directory structure looks different now:
> 
> ```
> # ls -al
> total 144
> drwxr-xr-x 14 root root  4096 Apr 18 01:20 .
> drwxr-xr-x  3 root root  4096 Apr 18 01:19 ..
> drwxr-xr-x  4 root root  4096 Apr 18 01:20 .bin
> -rw-r--r--  1 root root   897 Apr 18 01:20 CONTRIBUTING.md
> -rw-r--r--  1 root root 39097 Apr 18 01:20 CONTRIBUTORS.md
> drwxr-xr-x  9 root root  4096 Apr 18 01:20 Discovery
> drwxr-xr-x 10 root root  4096 Apr 18 01:20 Fuzzing
> drwxr-xr-x  8 root root  4096 Apr 18 01:20 .git
> -rw-r--r--  1 root root    47 Apr 18 01:20 .gitattributes
> drwxr-xr-x  5 root root  4096 Apr 18 01:20 .github
> -rw-r--r--  1 root root    51 Apr 18 01:20 .gitignore
> drwxr-xr-x  2 root root  4096 Apr 18 01:20 IOCs
> -rw-r--r--  1 root root  1072 Apr 18 01:20 LICENSE
> drwxr-xr-x  9 root root  4096 Apr 18 01:20 Miscellaneous
> drwxr-xr-x 17 root root  4096 Apr 18 01:20 Passwords
> drwxr-xr-x  3 root root  4096 Apr 18 01:20 Pattern-Matching
> drwxr-xr-x  8 root root  4096 Apr 18 01:20 Payloads
> -rw-r--r--  1 root root  2425 Apr 18 01:20 README.md
> -rw-r--r--  1 root root 25353 Apr 18 01:20 SecLists.png
> drwxr-xr-x  4 root root  4096 Apr 18 01:20 Usernames
> drwxr-xr-x 10 root root  4096 Apr 18 01:20 Web-Shells
> ```
