### ISSUE TITLE
Running Metasploit after installing with PTF

### ISSUE THREAD

**Issue by smittix** [trustedsec/ptf#70]
Hi All,

I have an issue where I cannot run Metasploit at all.

I have the following error.

Gem::InstallError: metasploit-concern requires Ruby version >= 2.1.

I am using Linux Mint 17.2

For some reason an older version of Ruby is installed but it looks as if PTF does install the latest version. 

Output from PTF

rvm 1.26.11 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
Already installed ruby-2.2.3.
To reinstall use:

    rvm reinstall ruby-2.2.3

Creating alias default for ruby-2.2.3....

---

But ruby -v says different?
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

**Comment by smittix** [comment]
Looks like I have corrected the problem. I manually installed RVM and switched Ruby versions and it seems to be working now.

**Comment by trustedsec** [comment]
Awesome  - glad to hear it. Haven't installed on mint specifically.. Do you have a list of the commands?
