### ISSUE TITLE
Minimal Ubuntu install issues (docker related?)

### ISSUE THREAD

**Issue by kosborn** [trustedsec/ptf#71]
I believe this is due to minimal ubuntu, but important point is that I am also running this in Docker.
(Docker, because I don't like my host system to have a million extra dependencies :smile:  )

Minimal ubuntu is from Docker's official hub, ubuntu:14.04 - x64

Some fails:

1. dradisframework requires libsqlite-dev (dradis-nessus -> bundle install sqlite specifically)
 * Fixed with ```apt-get install libsqlite-dev```
2. Wine package is only available as wine1.6-i386, so you must add
 * Fixed with ```sudo dpkg --add-architecture i386```
3. Need to update X64_LOCATION, otherwise the cp/untar filename is wrong
 * Fixed by appending /download like so: ```X64_LOCATION=....HconSTF_v0.5_Prime_Linux_x64.tar.bz2/download```

Things that could use more automation:
* Kerberos service 
* CPAN mirror
* openvas SVN cert
* backdoorfactory does an apt-get intsall and prompts to continue
* empire also require apt-get installs and then wants a server password 

Will update with any other failures.

**Comment by trustedsec** [comment]
Thanks for all of these Kos - went through and fixed, committing now. *hugs*
