### ISSUE TITLE
 No such file or directory: 'HconSTF'

### ISSUE THREAD

**Issue by oncee** [trustedsec/ptf#72]
cp: cannot stat ‘download’: No such file or directory
[*] Sending after command: bzip2 -d download.tar.bz2
bzip2: Can't open input file download.tar.bz2: No such file or directory.
[*] Sending after command: tar -xf download.tar
tar: download.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
[*] Sending after command: cd HconSTF
[!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.
[!] It's not possible its due to my coding skillz, it must be you? :-)
[!] Printing that error. Get that error. You get it: [Errno 2] No such file or directory: 'HconSTF'

**Comment by trustedsec** [comment]
Thanks Bill! Fixed and pushing release out here shortly.
