### ISSUE TITLE
Metasploit install broken

### ISSUE THREAD

**Issue by masterofoz** [trustedsec/ptf#75]
Hi!
I have tested ptf on a virtual Ubuntu 14.04.3 amd64 desktop.
This is a newly installed Ubuntu VM with no other programs (except what is default) installed.
I choose to install all modules, unfortunatelly the one I am most interested in, Metasploit, won't work.

If I run "use modules/install_update_all" I get this error when it comes to Metasploit:

"Installing metasploit-concern 1.0.0

Gem::InstallError: metasploit-concern requires Ruby version >= 2.1.
An error occurred while installing metasploit-concern (1.0.0), and Bundler cannot continue.
Make sure that `gem install metasploit-concern -v '1.0.0'` succeeds before bundling.
[*] Killing ruby gem launchers as this breaks launchers...
rm: cannot remove ‘/usr/local/rvm/gems/ruby-2.*/bin/msf*’: No such file or directory
[*] Finished updating Metasploit.... Enjoy!"

If I then try to run metasploit I get this error:

janne@ubuntu:~$ msfconsole
chmod: changing permissions of ‘msfconsole’: Operation not permitted
[*] Metasploit requires the Bundler gem to be installed
    $ gem install bundler

janne@ubuntu:~$ sudo msfconsole
[sudo] password for janne: 
Could not find metasploit-concern-1.0.0 in any of the sources
Run `bundle install` to install missing gems.

janne@ubuntu:~$ bundle install
/usr/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find bundler (>= 0) amongst [bundler-unload-1.0.2, executable-hooks-1.3.2, gem-wrappers-1.2.7, rubygems-bundler-1.4.4, rvm-1.11.3.9] (Gem::LoadError)
from /usr/lib/ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
from /usr/lib/ruby/1.9.1/rubygems.rb:1231:in `gem'
from /usr/local/bin/bundle:22:in `<main>'
janne@ubuntu:~$ 

Do you know why this happens and how it can be resolved?

**Comment by smittix** [comment]
I had the same issue on Mint and you can resolve it by manually updating
ruby yourself and setting which version the system uses but it will revert
when you run an update on PTF

**Comment by trustedsec** [comment]
I'm running Ubuntu 14.04 on mine - seems to work but will test out of the box with an iso tonight to troubleshoot.

**Comment by smittix** [comment]
If any futher testing is needed please let me know, I will be glad to help.

**Comment by trustedsec** [comment]
Can confirm this is an issue - will start working on this tomorrow.

**Comment by trustedsec** [comment]
Still working on this one - I'm with slow internet at the moment in Europe, get back tonight. Top priority fixing though.

**Comment by trustedsec** [comment]
Located the issue - no direct resolution yet. Main problem is the source /etc/profile.d/rvm.sh - there's no source in subprocess because thats bash specific. I'm working on getting it on a workaround.. Getting closer.

**Comment by trustedsec** [comment]
Finally! Licked this one. The new version of PTF just released fixes the Metasploit install issue. Tested on a brand new Ubuntu install. Let me know if you run into any issues.
