### ISSUE TITLE
do NOT automatically install external dependencies system-wide

### ISSUE THREAD

**Issue by mattoufoutu** [trustedsec/ptf#81]
Currently, whenever a tool has dependencies defined in a `requirements.txt`/`Gemfile`, these are installed system-wide, no matter if these are available using the distro's package manager, and no matter if these are already installed using the distro's package manager, without even warning the user about it.

This might (and, at some point, will) break things on the system, as this would overwrite files already installed by the package manager with a possibly different version, and other system applications may not be compatible with the newly installed version. This has just overwritten a bunch of packages that I already had installed using `apt`, and now I'm just waiting to discover what this might have broken on my system... :rage:

Installing these dependencies should not be done system-wide, but inside a virtual environment (using `virtualenv`/`rvm`/whatever), be it on a per-tool basis, or globally for all the tools handled by `ptf` (a per-tool environment might be cleaner as all the tools may not depend on the same versions of packages), or the user should be notified before such a thing occurs, so he has a chance to stop the installation process.

**Comment by trustedsec** [comment]
RVM is messed based on source variables through subprocess. Metasploit is a tough one to install and requires a bunch of requirements for install. Would recommend checking out the source before installing files.

**Comment by trustedsec** [comment]
Also - we accept pull requests, if you can get metasploit working without doing this, please feel free to do a git pull.

**Comment by mattoufoutu** [comment]
I didn't say it was easy or even a viable solution, this would just be the ideal solution.
Yet, warning the user before overwriting a bunch of his system packages would be nice...

**Comment by trustedsec** [comment]
I test whats on my own system and other platforms. If you find something thats broken or want a warning, you can submit a pull request and I can look at that to see if its viable to add.
