### ISSUE TITLE
Prereqs for dotdotpwn don't seem to be installed

### ISSUE THREAD

**Issue by sempf** [trustedsec/ptf#83]
When running dotdotpwn in Ubuntu I get the following:

Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: . /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl) at DotDotPwn/TraversalEngine.pm line 30.
BEGIN failed--compilation aborted at DotDotPwn/TraversalEngine.pm line 30.
Compilation failed in require at ./dotdotpwn.pl line 56.
BEGIN failed--compilation aborted at ./dotdotpwn.pl line 56.

I can work on this tomorrow, but the issue should be raised.

**Comment by trustedsec** [comment]
Fixed, added TFTP and Switch perl reqs through cpan - will need to rm -rf directory and re-run module :)
