### ISSUE TITLE
ftpmap prerequisites not installed

### ISSUE THREAD

**Issue by sempf** [trustedsec/ptf#85]
ftpmap wasn't working on my install, so I ran the install steps manually, and discovered:

sempf@sempf-Aspire-S7-391:/pentest/vulnerability-analysis/ftpmap$ sudo make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /pentest/vulnerability-analysis/ftpmap/missing aclocal-1.15 
/pentest/vulnerability-analysis/ftpmap/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [aclocal.m4] Error 127

I can look at these tomorrow and put in a pull but the issue should be reported.

S

**Comment by trustedsec** [comment]
Fixed, you'll need to rm -rf /pentest/vulnerability-analysis/ftpmap and rerun the module. Issue was Ubuntu only has aclocal-1.14 not aclocal-1.15, ive since moved to building from source and updated the module to reflex. Thanks for the report!

**Comment by sempf** [comment]
Oh, thanks!  You don't have to fix them, I'm willing to put in pull requests later.  But I appreciate it.

S
