### ISSUE TITLE
Writing a Logfile

### ISSUE THREAD

**Issue by hawaii67** [trustedsec/ptf#87]
If using  modules/install_update_all it would be nice if a logfile would be written (with the date attached to the name) each time this module is run so that you can enumerate what has when been updated, even after days or weeks. 
For me it would be important to check which tools have been updated and which packages have been installed/modified (since some packages break other packages!).

**Comment by trustedsec** [comment]
I'll add this to a milestone and not an issue tracking - this shouldn't be a problem but it would most likely be console output from the time being and timestamp should be pretty easy.

**Comment by hawaii67** [comment]
Ok, thanks a lot!  :-)
Cheers
